// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Tệp HWP đang mở. Luôn là bản sao app sở hữu, không phải tệp gốc của người
/// dùng.
class HwpDocument {
  HwpDocument({
    required this.path,
    required this.fileName,
    required this.fileFormat,
    required this.fileSizeBytes,
  });

  String path;

  String fileName;

  /// `hwp` hoặc `hwpx`.
  String fileFormat;

  int fileSizeBytes;

  List<Object?> _toList() {
    return <Object?>[path, fileName, fileFormat, fileSizeBytes];
  }

  Object encode() {
    return _toList();
  }

  static HwpDocument decode(Object result) {
    result as List<Object?>;
    return HwpDocument(
      path: result[0]! as String,
      fileName: result[1]! as String,
      fileFormat: result[2]! as String,
      fileSizeBytes: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpDocument || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(fileFormat, other.fileFormat) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpDocument(path: $path, fileName: $fileName, fileFormat: $fileFormat, fileSizeBytes: $fileSizeBytes)';
  }
}

/// Trạng thái con trỏ trong trình soạn thảo, đủ để vẽ thanh công cụ.
///
/// Con trỏ và vùng chọn sống trong trang vỏ chứ không trong tài liệu — rhwp
/// không giữ chúng — nên đây là ảnh chụp đẩy ngược lên, không phải nguồn sự
/// thật để ghi xuống.
class HwpEditorState {
  HwpEditorState({
    required this.hasCaret,
    required this.hasSelection,
    required this.bold,
    required this.italic,
    required this.underline,
    required this.strikethrough,
    this.fontSizePt,
    this.alignment,
    this.lineSpacing,
    required this.canUndo,
    required this.canRedo,
    required this.dirty,
    required this.pageIndex,
    required this.pageCount,
  });

  bool hasCaret;

  bool hasSelection;

  bool bold;

  bool italic;

  bool underline;

  bool strikethrough;

  /// Cỡ chữ theo **điểm**. rhwp lưu theo HWPUNIT (pt × 100); phép chia nằm ở
  /// trang vỏ để bên Flutter không phải biết đơn vị của định dạng tệp.
  double? fontSizePt;

  /// `left`, `center`, `right`, `justify` hoặc `distribute`.
  String? alignment;

  double? lineSpacing;

  bool canUndo;

  bool canRedo;

  /// Có thay đổi chưa ghi xuống tệp. Tắt chế độ sửa khi đang bật cờ này là mất
  /// thay đổi.
  bool dirty;

  /// Trang đang hiển thị, đếm từ 0.
  int pageIndex;

  /// Tổng số trang, luôn ít nhất là 1.
  ///
  /// Đổi được **trong lúc sửa**: gõ thêm chữ có thể làm tài liệu nở ra hoặc co
  /// lại một trang, nên thanh lật trang phải đọc lại con số này chứ không nhớ
  /// giá trị lúc mở tệp.
  int pageCount;

  List<Object?> _toList() {
    return <Object?>[
      hasCaret,
      hasSelection,
      bold,
      italic,
      underline,
      strikethrough,
      fontSizePt,
      alignment,
      lineSpacing,
      canUndo,
      canRedo,
      dirty,
      pageIndex,
      pageCount,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HwpEditorState decode(Object result) {
    result as List<Object?>;
    return HwpEditorState(
      hasCaret: result[0]! as bool,
      hasSelection: result[1]! as bool,
      bold: result[2]! as bool,
      italic: result[3]! as bool,
      underline: result[4]! as bool,
      strikethrough: result[5]! as bool,
      fontSizePt: result[6] as double?,
      alignment: result[7] as String?,
      lineSpacing: result[8] as double?,
      canUndo: result[9]! as bool,
      canRedo: result[10]! as bool,
      dirty: result[11]! as bool,
      pageIndex: result[12]! as int,
      pageCount: result[13]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpEditorState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasCaret, other.hasCaret) &&
        _deepEquals(hasSelection, other.hasSelection) &&
        _deepEquals(bold, other.bold) &&
        _deepEquals(italic, other.italic) &&
        _deepEquals(underline, other.underline) &&
        _deepEquals(strikethrough, other.strikethrough) &&
        _deepEquals(fontSizePt, other.fontSizePt) &&
        _deepEquals(alignment, other.alignment) &&
        _deepEquals(lineSpacing, other.lineSpacing) &&
        _deepEquals(canUndo, other.canUndo) &&
        _deepEquals(canRedo, other.canRedo) &&
        _deepEquals(dirty, other.dirty) &&
        _deepEquals(pageIndex, other.pageIndex) &&
        _deepEquals(pageCount, other.pageCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpEditorState(hasCaret: $hasCaret, hasSelection: $hasSelection, bold: $bold, italic: $italic, underline: $underline, strikethrough: $strikethrough, fontSizePt: $fontSizePt, alignment: $alignment, lineSpacing: $lineSpacing, canUndo: $canUndo, canRedo: $canRedo, dirty: $dirty, pageIndex: $pageIndex, pageCount: $pageCount)';
  }
}

/// Định dạng chữ cần áp. Khoá nào `null` thì giữ nguyên — bật đậm không được
/// phép lặng lẽ đặt lại cỡ chữ.
class HwpCharFormat {
  HwpCharFormat({this.bold, this.italic, this.underline, this.strikethrough, this.fontSizePt});

  bool? bold;

  bool? italic;

  bool? underline;

  bool? strikethrough;

  double? fontSizePt;

  List<Object?> _toList() {
    return <Object?>[bold, italic, underline, strikethrough, fontSizePt];
  }

  Object encode() {
    return _toList();
  }

  static HwpCharFormat decode(Object result) {
    result as List<Object?>;
    return HwpCharFormat(
      bold: result[0] as bool?,
      italic: result[1] as bool?,
      underline: result[2] as bool?,
      strikethrough: result[3] as bool?,
      fontSizePt: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpCharFormat || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bold, other.bold) &&
        _deepEquals(italic, other.italic) &&
        _deepEquals(underline, other.underline) &&
        _deepEquals(strikethrough, other.strikethrough) &&
        _deepEquals(fontSizePt, other.fontSizePt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpCharFormat(bold: $bold, italic: $italic, underline: $underline, strikethrough: $strikethrough, fontSizePt: $fontSizePt)';
  }
}

/// Định dạng đoạn cần áp. Cùng quy ước `null` là giữ nguyên như
/// [HwpCharFormat].
class HwpParaFormat {
  HwpParaFormat({this.alignment, this.lineSpacing});

  String? alignment;

  double? lineSpacing;

  List<Object?> _toList() {
    return <Object?>[alignment, lineSpacing];
  }

  Object encode() {
    return _toList();
  }

  static HwpParaFormat decode(Object result) {
    result as List<Object?>;
    return HwpParaFormat(alignment: result[0] as String?, lineSpacing: result[1] as double?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpParaFormat || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alignment, other.alignment) && _deepEquals(lineSpacing, other.lineSpacing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpParaFormat(alignment: $alignment, lineSpacing: $lineSpacing)';
  }
}

/// Kết quả một lần ghi tài liệu xuống đĩa.
class HwpSaveResult {
  HwpSaveResult({required this.ok, this.contentLoss, this.error});

  bool ok;

  /// Báo cáo phần nội dung trình xuất phải bỏ đi, lấy từ
  /// `exportHwpWithReport`. Không rỗng nghĩa là tệp ghi ra **không** giữ đủ
  /// tài liệu ban đầu, kể cả khi [ok].
  String? contentLoss;

  String? error;

  List<Object?> _toList() {
    return <Object?>[ok, contentLoss, error];
  }

  Object encode() {
    return _toList();
  }

  static HwpSaveResult decode(Object result) {
    result as List<Object?>;
    return HwpSaveResult(
      ok: result[0]! as bool,
      contentLoss: result[1] as String?,
      error: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpSaveResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ok, other.ok) &&
        _deepEquals(contentLoss, other.contentLoss) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpSaveResult(ok: $ok, contentLoss: $contentLoss, error: $error)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HwpDocument) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is HwpEditorState) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is HwpCharFormat) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is HwpParaFormat) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is HwpSaveResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return HwpDocument.decode(readValue(buffer)!);
      case 130:
        return HwpEditorState.decode(readValue(buffer)!);
      case 131:
        return HwpCharFormat.decode(readValue(buffer)!);
      case 132:
        return HwpParaFormat.decode(readValue(buffer)!);
      case 133:
        return HwpSaveResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HwpHostApi {
  /// Constructor for [HwpHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HwpHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Nạp tệp vào trình xem đang gắn trên màn hình.
  Future<void> loadDocument(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.loadDocument$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Chuyển sang chế độ sửa, hoặc quay lại chỉ xem.
  ///
  /// Tắt sẽ **bỏ mọi thay đổi chưa lưu** — chúng chỉ nằm trong trình soạn
  /// thảo, không nằm trong tệp.
  Future<void> setEditingEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.setEditingEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Ghi tài liệu đang sửa đè lên tệp đang mở.
  ///
  /// Trả về ngay; việc xuất chạy bất đồng bộ trong trang vỏ và kết quả về qua
  /// `onEditsSaved`.
  Future<void> saveEdits() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.saveEdits$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Áp định dạng chữ lên vùng đang chọn.
  ///
  /// Không có vùng chọn thì định dạng được giữ lại và áp cho đoạn chữ gõ tiếp
  /// theo, giống mọi trình soạn thảo khác.
  Future<void> applyCharFormat(HwpCharFormat format) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.applyCharFormat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[format]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Áp định dạng lên đoạn văn đang chứa con trỏ, hoặc mọi đoạn mà vùng chọn
  /// chạm tới.
  Future<void> applyParaFormat(HwpParaFormat format) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.applyParaFormat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[format]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Cho trang vỏ biết Flutter đang che mất bao nhiêu điểm ở đáy web view —
  /// tức chiều cao thanh công cụ nổi.
  ///
  /// Bàn phím thì native tự đo được; chỗ này chỉ nói về phần giao diện của
  /// Flutter, thứ native không nhìn thấy. Con trỏ phải tránh cả hai.
  Future<void> setChromeInset(double pixels) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.setChromeInset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pixels]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Hoàn tác bước sửa gần nhất. Ngăn xếp nằm trong trang vỏ và mất khi tắt
  /// chế độ sửa.
  Future<void> undo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.undo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> redo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.redo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Lật tới trang `pageIndex`, đếm từ 0. Chỉ số ngoài phạm vi bị kẹp về đầu
  /// hoặc cuối chứ không báo lỗi.
  Future<void> goToPage(int pageIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.goToPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pageIndex]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Tìm kết quả kế tiếp hoặc trước đó. Trả về có tìm thấy và chọn được không.
  Future<bool> find(String query, bool forward) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.find$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[query, forward]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> clearSearch() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.clearSearch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Chia sẻ tệp đang mở qua bảng chia sẻ của hệ thống.
  Future<void> share() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.share$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Nhả trình xem và xoá bản sao cục bộ.
  Future<void> close() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.close$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}

abstract class HwpFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Con trỏ, vùng chọn hoặc nội dung vừa đổi.
  void onEditorStateChanged(HwpEditorState state);

  /// Một lần ghi tài liệu đã xong — thành công hay không.
  void onEditsSaved(HwpSaveResult result);

  static void setUp(
    HwpFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.HwpFlutterApi.onEditorStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final HwpEditorState arg_state = args[0]! as HwpEditorState;
          try {
            api.onEditorStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.HwpFlutterApi.onEditsSaved$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final HwpSaveResult arg_result = args[0]! as HwpSaveResult;
          try {
            api.onEditsSaved(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
