// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum HwpApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Tệp HWP đang mở. Luôn là bản sao app sở hữu, không phải tệp gốc của người
/// dùng.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HwpDocument: Hashable, CustomStringConvertible {
  var path: String
  var fileName: String
  /// `hwp` hoặc `hwpx`.
  var fileFormat: String
  var fileSizeBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HwpDocument? {
    let path = pigeonVar_list[0] as! String
    let fileName = pigeonVar_list[1] as! String
    let fileFormat = pigeonVar_list[2] as! String
    let fileSizeBytes = pigeonVar_list[3] as! Int64

    return HwpDocument(
      path: path,
      fileName: fileName,
      fileFormat: fileFormat,
      fileSizeBytes: fileSizeBytes
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      fileName,
      fileFormat,
      fileSizeBytes,
    ]
  }
  static func == (lhs: HwpDocument, rhs: HwpDocument) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HwpApiPigeonInternal.deepEquals(lhs.path, rhs.path) && HwpApiPigeonInternal.deepEquals(lhs.fileName, rhs.fileName) && HwpApiPigeonInternal.deepEquals(lhs.fileFormat, rhs.fileFormat) && HwpApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HwpDocument")
    HwpApiPigeonInternal.deepHash(value: path, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: fileName, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: fileFormat, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
  }

  public var description: String {
    return "HwpDocument(path: \(String(describing: path)), fileName: \(String(describing: fileName)), fileFormat: \(String(describing: fileFormat)), fileSizeBytes: \(String(describing: fileSizeBytes)))"
  }
}

/// Trạng thái con trỏ trong trình soạn thảo, đủ để vẽ thanh công cụ.
///
/// Con trỏ và vùng chọn sống trong trang vỏ chứ không trong tài liệu — rhwp
/// không giữ chúng — nên đây là ảnh chụp đẩy ngược lên, không phải nguồn sự
/// thật để ghi xuống.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HwpEditorState: Hashable, CustomStringConvertible {
  var hasCaret: Bool
  var hasSelection: Bool
  var bold: Bool
  var italic: Bool
  var underline: Bool
  var strikethrough: Bool
  /// Cỡ chữ theo **điểm**. rhwp lưu theo HWPUNIT (pt × 100); phép chia nằm ở
  /// trang vỏ để bên Flutter không phải biết đơn vị của định dạng tệp.
  var fontSizePt: Double? = nil
  /// `left`, `center`, `right`, `justify` hoặc `distribute`.
  var alignment: String? = nil
  var lineSpacing: Double? = nil
  var canUndo: Bool
  var canRedo: Bool
  /// Có thay đổi chưa ghi xuống tệp. Tắt chế độ sửa khi đang bật cờ này là mất
  /// thay đổi.
  var dirty: Bool
  /// Trang đang hiển thị, đếm từ 0.
  var pageIndex: Int64
  /// Tổng số trang, luôn ít nhất là 1.
  ///
  /// Đổi được **trong lúc sửa**: gõ thêm chữ có thể làm tài liệu nở ra hoặc co
  /// lại một trang, nên thanh lật trang phải đọc lại con số này chứ không nhớ
  /// giá trị lúc mở tệp.
  var pageCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HwpEditorState? {
    let hasCaret = pigeonVar_list[0] as! Bool
    let hasSelection = pigeonVar_list[1] as! Bool
    let bold = pigeonVar_list[2] as! Bool
    let italic = pigeonVar_list[3] as! Bool
    let underline = pigeonVar_list[4] as! Bool
    let strikethrough = pigeonVar_list[5] as! Bool
    let fontSizePt: Double? = nilOrValue(pigeonVar_list[6])
    let alignment: String? = nilOrValue(pigeonVar_list[7])
    let lineSpacing: Double? = nilOrValue(pigeonVar_list[8])
    let canUndo = pigeonVar_list[9] as! Bool
    let canRedo = pigeonVar_list[10] as! Bool
    let dirty = pigeonVar_list[11] as! Bool
    let pageIndex = pigeonVar_list[12] as! Int64
    let pageCount = pigeonVar_list[13] as! Int64

    return HwpEditorState(
      hasCaret: hasCaret,
      hasSelection: hasSelection,
      bold: bold,
      italic: italic,
      underline: underline,
      strikethrough: strikethrough,
      fontSizePt: fontSizePt,
      alignment: alignment,
      lineSpacing: lineSpacing,
      canUndo: canUndo,
      canRedo: canRedo,
      dirty: dirty,
      pageIndex: pageIndex,
      pageCount: pageCount
    )
  }
  func toList() -> [Any?] {
    return [
      hasCaret,
      hasSelection,
      bold,
      italic,
      underline,
      strikethrough,
      fontSizePt,
      alignment,
      lineSpacing,
      canUndo,
      canRedo,
      dirty,
      pageIndex,
      pageCount,
    ]
  }
  static func == (lhs: HwpEditorState, rhs: HwpEditorState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HwpApiPigeonInternal.deepEquals(lhs.hasCaret, rhs.hasCaret) && HwpApiPigeonInternal.deepEquals(lhs.hasSelection, rhs.hasSelection) && HwpApiPigeonInternal.deepEquals(lhs.bold, rhs.bold) && HwpApiPigeonInternal.deepEquals(lhs.italic, rhs.italic) && HwpApiPigeonInternal.deepEquals(lhs.underline, rhs.underline) && HwpApiPigeonInternal.deepEquals(lhs.strikethrough, rhs.strikethrough) && HwpApiPigeonInternal.deepEquals(lhs.fontSizePt, rhs.fontSizePt) && HwpApiPigeonInternal.deepEquals(lhs.alignment, rhs.alignment) && HwpApiPigeonInternal.deepEquals(lhs.lineSpacing, rhs.lineSpacing) && HwpApiPigeonInternal.deepEquals(lhs.canUndo, rhs.canUndo) && HwpApiPigeonInternal.deepEquals(lhs.canRedo, rhs.canRedo) && HwpApiPigeonInternal.deepEquals(lhs.dirty, rhs.dirty) && HwpApiPigeonInternal.deepEquals(lhs.pageIndex, rhs.pageIndex) && HwpApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HwpEditorState")
    HwpApiPigeonInternal.deepHash(value: hasCaret, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: hasSelection, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: bold, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: italic, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: underline, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: strikethrough, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: fontSizePt, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: alignment, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: lineSpacing, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: canUndo, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: canRedo, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: dirty, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: pageIndex, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
  }

  public var description: String {
    return "HwpEditorState(hasCaret: \(String(describing: hasCaret)), hasSelection: \(String(describing: hasSelection)), bold: \(String(describing: bold)), italic: \(String(describing: italic)), underline: \(String(describing: underline)), strikethrough: \(String(describing: strikethrough)), fontSizePt: \(String(describing: fontSizePt)), alignment: \(String(describing: alignment)), lineSpacing: \(String(describing: lineSpacing)), canUndo: \(String(describing: canUndo)), canRedo: \(String(describing: canRedo)), dirty: \(String(describing: dirty)), pageIndex: \(String(describing: pageIndex)), pageCount: \(String(describing: pageCount)))"
  }
}

/// Định dạng chữ cần áp. Khoá nào `null` thì giữ nguyên — bật đậm không được
/// phép lặng lẽ đặt lại cỡ chữ.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HwpCharFormat: Hashable, CustomStringConvertible {
  var bold: Bool? = nil
  var italic: Bool? = nil
  var underline: Bool? = nil
  var strikethrough: Bool? = nil
  var fontSizePt: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HwpCharFormat? {
    let bold: Bool? = nilOrValue(pigeonVar_list[0])
    let italic: Bool? = nilOrValue(pigeonVar_list[1])
    let underline: Bool? = nilOrValue(pigeonVar_list[2])
    let strikethrough: Bool? = nilOrValue(pigeonVar_list[3])
    let fontSizePt: Double? = nilOrValue(pigeonVar_list[4])

    return HwpCharFormat(
      bold: bold,
      italic: italic,
      underline: underline,
      strikethrough: strikethrough,
      fontSizePt: fontSizePt
    )
  }
  func toList() -> [Any?] {
    return [
      bold,
      italic,
      underline,
      strikethrough,
      fontSizePt,
    ]
  }
  static func == (lhs: HwpCharFormat, rhs: HwpCharFormat) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HwpApiPigeonInternal.deepEquals(lhs.bold, rhs.bold) && HwpApiPigeonInternal.deepEquals(lhs.italic, rhs.italic) && HwpApiPigeonInternal.deepEquals(lhs.underline, rhs.underline) && HwpApiPigeonInternal.deepEquals(lhs.strikethrough, rhs.strikethrough) && HwpApiPigeonInternal.deepEquals(lhs.fontSizePt, rhs.fontSizePt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HwpCharFormat")
    HwpApiPigeonInternal.deepHash(value: bold, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: italic, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: underline, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: strikethrough, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: fontSizePt, hasher: &hasher)
  }

  public var description: String {
    return "HwpCharFormat(bold: \(String(describing: bold)), italic: \(String(describing: italic)), underline: \(String(describing: underline)), strikethrough: \(String(describing: strikethrough)), fontSizePt: \(String(describing: fontSizePt)))"
  }
}

/// Định dạng đoạn cần áp. Cùng quy ước `null` là giữ nguyên như
/// [HwpCharFormat].
///
/// Generated class from Pigeon that represents data sent in messages.
struct HwpParaFormat: Hashable, CustomStringConvertible {
  var alignment: String? = nil
  var lineSpacing: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HwpParaFormat? {
    let alignment: String? = nilOrValue(pigeonVar_list[0])
    let lineSpacing: Double? = nilOrValue(pigeonVar_list[1])

    return HwpParaFormat(
      alignment: alignment,
      lineSpacing: lineSpacing
    )
  }
  func toList() -> [Any?] {
    return [
      alignment,
      lineSpacing,
    ]
  }
  static func == (lhs: HwpParaFormat, rhs: HwpParaFormat) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HwpApiPigeonInternal.deepEquals(lhs.alignment, rhs.alignment) && HwpApiPigeonInternal.deepEquals(lhs.lineSpacing, rhs.lineSpacing)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HwpParaFormat")
    HwpApiPigeonInternal.deepHash(value: alignment, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: lineSpacing, hasher: &hasher)
  }

  public var description: String {
    return "HwpParaFormat(alignment: \(String(describing: alignment)), lineSpacing: \(String(describing: lineSpacing)))"
  }
}

/// Kết quả một lần ghi tài liệu xuống đĩa.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HwpSaveResult: Hashable, CustomStringConvertible {
  var ok: Bool
  /// Báo cáo phần nội dung trình xuất phải bỏ đi, lấy từ
  /// `exportHwpWithReport`. Không rỗng nghĩa là tệp ghi ra **không** giữ đủ
  /// tài liệu ban đầu, kể cả khi [ok].
  var contentLoss: String? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HwpSaveResult? {
    let ok = pigeonVar_list[0] as! Bool
    let contentLoss: String? = nilOrValue(pigeonVar_list[1])
    let error: String? = nilOrValue(pigeonVar_list[2])

    return HwpSaveResult(
      ok: ok,
      contentLoss: contentLoss,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      ok,
      contentLoss,
      error,
    ]
  }
  static func == (lhs: HwpSaveResult, rhs: HwpSaveResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HwpApiPigeonInternal.deepEquals(lhs.ok, rhs.ok) && HwpApiPigeonInternal.deepEquals(lhs.contentLoss, rhs.contentLoss) && HwpApiPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HwpSaveResult")
    HwpApiPigeonInternal.deepHash(value: ok, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: contentLoss, hasher: &hasher)
    HwpApiPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "HwpSaveResult(ok: \(String(describing: ok)), contentLoss: \(String(describing: contentLoss)), error: \(String(describing: error)))"
  }
}

private class HwpApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return HwpDocument.fromList(self.readValue() as! [Any?])
    case 130:
      return HwpEditorState.fromList(self.readValue() as! [Any?])
    case 131:
      return HwpCharFormat.fromList(self.readValue() as! [Any?])
    case 132:
      return HwpParaFormat.fromList(self.readValue() as! [Any?])
    case 133:
      return HwpSaveResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HwpApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HwpDocument {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? HwpEditorState {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? HwpCharFormat {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? HwpParaFormat {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? HwpSaveResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HwpApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HwpApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HwpApiPigeonCodecWriter(data: data)
  }
}

class HwpApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HwpApiPigeonCodec(readerWriter: HwpApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HwpHostApi {
  /// Nạp tệp vào trình xem đang gắn trên màn hình.
  func loadDocument(path: String) throws
  /// Chuyển sang chế độ sửa, hoặc quay lại chỉ xem.
  ///
  /// Tắt sẽ **bỏ mọi thay đổi chưa lưu** — chúng chỉ nằm trong trình soạn
  /// thảo, không nằm trong tệp.
  func setEditingEnabled(enabled: Bool) throws
  /// Ghi tài liệu đang sửa đè lên tệp đang mở.
  ///
  /// Trả về ngay; việc xuất chạy bất đồng bộ trong trang vỏ và kết quả về qua
  /// `onEditsSaved`.
  func saveEdits() throws
  /// Áp định dạng chữ lên vùng đang chọn.
  ///
  /// Không có vùng chọn thì định dạng được giữ lại và áp cho đoạn chữ gõ tiếp
  /// theo, giống mọi trình soạn thảo khác.
  func applyCharFormat(format: HwpCharFormat) throws
  /// Áp định dạng lên đoạn văn đang chứa con trỏ, hoặc mọi đoạn mà vùng chọn
  /// chạm tới.
  func applyParaFormat(format: HwpParaFormat) throws
  /// Cho trang vỏ biết Flutter đang che mất bao nhiêu điểm ở đáy web view —
  /// tức chiều cao thanh công cụ nổi.
  ///
  /// Bàn phím thì native tự đo được; chỗ này chỉ nói về phần giao diện của
  /// Flutter, thứ native không nhìn thấy. Con trỏ phải tránh cả hai.
  func setChromeInset(pixels: Double) throws
  /// Hoàn tác bước sửa gần nhất. Ngăn xếp nằm trong trang vỏ và mất khi tắt
  /// chế độ sửa.
  func undo() throws
  func redo() throws
  /// Lật tới trang `pageIndex`, đếm từ 0. Chỉ số ngoài phạm vi bị kẹp về đầu
  /// hoặc cuối chứ không báo lỗi.
  func goToPage(pageIndex: Int64) throws
  /// Tìm kết quả kế tiếp hoặc trước đó. Trả về có tìm thấy và chọn được không.
  func find(query: String, forward: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func clearSearch() throws
  /// Chia sẻ tệp đang mở qua bảng chia sẻ của hệ thống.
  func share() throws
  /// Nhả trình xem và xoá bản sao cục bộ.
  func close() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HwpHostApiSetup {
  static var codec: FlutterStandardMessageCodec { HwpApiPigeonCodec.shared }
  /// Sets up an instance of `HwpHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HwpHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Nạp tệp vào trình xem đang gắn trên màn hình.
    let loadDocumentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.loadDocument\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadDocumentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.loadDocument(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadDocumentChannel.setMessageHandler(nil)
    }
    /// Chuyển sang chế độ sửa, hoặc quay lại chỉ xem.
    ///
    /// Tắt sẽ **bỏ mọi thay đổi chưa lưu** — chúng chỉ nằm trong trình soạn
    /// thảo, không nằm trong tệp.
    let setEditingEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.setEditingEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setEditingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setEditingEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setEditingEnabledChannel.setMessageHandler(nil)
    }
    /// Ghi tài liệu đang sửa đè lên tệp đang mở.
    ///
    /// Trả về ngay; việc xuất chạy bất đồng bộ trong trang vỏ và kết quả về qua
    /// `onEditsSaved`.
    let saveEditsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.saveEdits\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveEditsChannel.setMessageHandler { _, reply in
        do {
          try api.saveEdits()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveEditsChannel.setMessageHandler(nil)
    }
    /// Áp định dạng chữ lên vùng đang chọn.
    ///
    /// Không có vùng chọn thì định dạng được giữ lại và áp cho đoạn chữ gõ tiếp
    /// theo, giống mọi trình soạn thảo khác.
    let applyCharFormatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.applyCharFormat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyCharFormatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let formatArg = args[0] as! HwpCharFormat
        do {
          try api.applyCharFormat(format: formatArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyCharFormatChannel.setMessageHandler(nil)
    }
    /// Áp định dạng lên đoạn văn đang chứa con trỏ, hoặc mọi đoạn mà vùng chọn
    /// chạm tới.
    let applyParaFormatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.applyParaFormat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyParaFormatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let formatArg = args[0] as! HwpParaFormat
        do {
          try api.applyParaFormat(format: formatArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyParaFormatChannel.setMessageHandler(nil)
    }
    /// Cho trang vỏ biết Flutter đang che mất bao nhiêu điểm ở đáy web view —
    /// tức chiều cao thanh công cụ nổi.
    ///
    /// Bàn phím thì native tự đo được; chỗ này chỉ nói về phần giao diện của
    /// Flutter, thứ native không nhìn thấy. Con trỏ phải tránh cả hai.
    let setChromeInsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.setChromeInset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setChromeInsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pixelsArg = args[0] as! Double
        do {
          try api.setChromeInset(pixels: pixelsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setChromeInsetChannel.setMessageHandler(nil)
    }
    /// Hoàn tác bước sửa gần nhất. Ngăn xếp nằm trong trang vỏ và mất khi tắt
    /// chế độ sửa.
    let undoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.undo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      undoChannel.setMessageHandler { _, reply in
        do {
          try api.undo()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      undoChannel.setMessageHandler(nil)
    }
    let redoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.redo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      redoChannel.setMessageHandler { _, reply in
        do {
          try api.redo()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      redoChannel.setMessageHandler(nil)
    }
    /// Lật tới trang `pageIndex`, đếm từ 0. Chỉ số ngoài phạm vi bị kẹp về đầu
    /// hoặc cuối chứ không báo lỗi.
    let goToPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.goToPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexArg = args[0] as! Int64
        do {
          try api.goToPage(pageIndex: pageIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToPageChannel.setMessageHandler(nil)
    }
    /// Tìm kết quả kế tiếp hoặc trước đó. Trả về có tìm thấy và chọn được không.
    let findChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.find\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      findChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        let forwardArg = args[1] as! Bool
        api.find(query: queryArg, forward: forwardArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      findChannel.setMessageHandler(nil)
    }
    let clearSearchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.clearSearch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSearchChannel.setMessageHandler { _, reply in
        do {
          try api.clearSearch()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSearchChannel.setMessageHandler(nil)
    }
    /// Chia sẻ tệp đang mở qua bảng chia sẻ của hệ thống.
    let shareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.share\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shareChannel.setMessageHandler { _, reply in
        do {
          try api.share()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      shareChannel.setMessageHandler(nil)
    }
    /// Nhả trình xem và xoá bản sao cục bộ.
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.HwpHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        do {
          try api.close()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HwpFlutterApiProtocol {
  /// Con trỏ, vùng chọn hoặc nội dung vừa đổi.
  func onEditorStateChanged(state stateArg: HwpEditorState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Một lần ghi tài liệu đã xong — thành công hay không.
  func onEditsSaved(result resultArg: HwpSaveResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HwpFlutterApi: HwpFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: HwpApiPigeonCodec {
    return HwpApiPigeonCodec.shared
  }
  /// Con trỏ, vùng chọn hoặc nội dung vừa đổi.
  func onEditorStateChanged(state stateArg: HwpEditorState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.HwpFlutterApi.onEditorStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Một lần ghi tài liệu đã xong — thành công hay không.
  func onEditsSaved(result resultArg: HwpSaveResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.HwpFlutterApi.onEditsSaved\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
