// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class HwpDocumentInfo {
  HwpDocumentInfo({
    required this.sessionId,
    required this.sourcePath,
    required this.fileName,
    required this.fileFormat,
    required this.fileSizeBytes,
    required this.pageCount,
    required this.isDirty,
    required this.canOverwriteSource,
    required this.engineVersion,
  });

  String sessionId;

  String sourcePath;

  String fileName;

  String fileFormat;

  int fileSizeBytes;

  int pageCount;

  bool isDirty;

  bool canOverwriteSource;

  String engineVersion;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      sourcePath,
      fileName,
      fileFormat,
      fileSizeBytes,
      pageCount,
      isDirty,
      canOverwriteSource,
      engineVersion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HwpDocumentInfo decode(Object result) {
    result as List<Object?>;
    return HwpDocumentInfo(
      sessionId: result[0]! as String,
      sourcePath: result[1]! as String,
      fileName: result[2]! as String,
      fileFormat: result[3]! as String,
      fileSizeBytes: result[4]! as int,
      pageCount: result[5]! as int,
      isDirty: result[6]! as bool,
      canOverwriteSource: result[7]! as bool,
      engineVersion: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpDocumentInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(fileFormat, other.fileFormat) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(isDirty, other.isDirty) &&
        _deepEquals(canOverwriteSource, other.canOverwriteSource) &&
        _deepEquals(engineVersion, other.engineVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpDocumentInfo(sessionId: $sessionId, sourcePath: $sourcePath, fileName: $fileName, fileFormat: $fileFormat, fileSizeBytes: $fileSizeBytes, pageCount: $pageCount, isDirty: $isDirty, canOverwriteSource: $canOverwriteSource, engineVersion: $engineVersion)';
  }
}

class HwpReplaceTextRequest {
  HwpReplaceTextRequest({
    required this.find,
    required this.replacement,
    required this.caseSensitive,
    required this.replaceAll,
  });

  String find;

  String replacement;

  bool caseSensitive;

  bool replaceAll;

  List<Object?> _toList() {
    return <Object?>[find, replacement, caseSensitive, replaceAll];
  }

  Object encode() {
    return _toList();
  }

  static HwpReplaceTextRequest decode(Object result) {
    result as List<Object?>;
    return HwpReplaceTextRequest(
      find: result[0]! as String,
      replacement: result[1]! as String,
      caseSensitive: result[2]! as bool,
      replaceAll: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpReplaceTextRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(find, other.find) &&
        _deepEquals(replacement, other.replacement) &&
        _deepEquals(caseSensitive, other.caseSensitive) &&
        _deepEquals(replaceAll, other.replaceAll);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpReplaceTextRequest(find: $find, replacement: $replacement, caseSensitive: $caseSensitive, replaceAll: $replaceAll)';
  }
}

class HwpEditResult {
  HwpEditResult({required this.replacementCount, required this.isDirty});

  int replacementCount;

  bool isDirty;

  List<Object?> _toList() {
    return <Object?>[replacementCount, isDirty];
  }

  Object encode() {
    return _toList();
  }

  static HwpEditResult decode(Object result) {
    result as List<Object?>;
    return HwpEditResult(
      replacementCount: result[0]! as int,
      isDirty: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpEditResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(replacementCount, other.replacementCount) &&
        _deepEquals(isDirty, other.isDirty);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpEditResult(replacementCount: $replacementCount, isDirty: $isDirty)';
  }
}

class HwpEditHistoryState {
  HwpEditHistoryState({
    required this.canUndo,
    required this.canRedo,
    required this.undoDepth,
    required this.redoDepth,
    required this.pageCount,
  });

  bool canUndo;

  bool canRedo;

  int undoDepth;

  int redoDepth;

  int pageCount;

  List<Object?> _toList() {
    return <Object?>[canUndo, canRedo, undoDepth, redoDepth, pageCount];
  }

  Object encode() {
    return _toList();
  }

  static HwpEditHistoryState decode(Object result) {
    result as List<Object?>;
    return HwpEditHistoryState(
      canUndo: result[0]! as bool,
      canRedo: result[1]! as bool,
      undoDepth: result[2]! as int,
      redoDepth: result[3]! as int,
      pageCount: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpEditHistoryState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(canUndo, other.canUndo) &&
        _deepEquals(canRedo, other.canRedo) &&
        _deepEquals(undoDepth, other.undoDepth) &&
        _deepEquals(redoDepth, other.redoDepth) &&
        _deepEquals(pageCount, other.pageCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpEditHistoryState(canUndo: $canUndo, canRedo: $canRedo, undoDepth: $undoDepth, redoDepth: $redoDepth, pageCount: $pageCount)';
  }
}

class HwpSaveResult {
  HwpSaveResult({
    required this.outputPath,
    required this.fileSizeBytes,
    required this.overwroteSource,
    required this.validated,
  });

  String outputPath;

  int fileSizeBytes;

  bool overwroteSource;

  bool validated;

  List<Object?> _toList() {
    return <Object?>[outputPath, fileSizeBytes, overwroteSource, validated];
  }

  Object encode() {
    return _toList();
  }

  static HwpSaveResult decode(Object result) {
    result as List<Object?>;
    return HwpSaveResult(
      outputPath: result[0]! as String,
      fileSizeBytes: result[1]! as int,
      overwroteSource: result[2]! as bool,
      validated: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HwpSaveResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(overwroteSource, other.overwroteSource) &&
        _deepEquals(validated, other.validated);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HwpSaveResult(outputPath: $outputPath, fileSizeBytes: $fileSizeBytes, overwroteSource: $overwroteSource, validated: $validated)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HwpDocumentInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is HwpReplaceTextRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is HwpEditResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is HwpEditHistoryState) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is HwpSaveResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return HwpDocumentInfo.decode(readValue(buffer)!);
      case 130:
        return HwpReplaceTextRequest.decode(readValue(buffer)!);
      case 131:
        return HwpEditResult.decode(readValue(buffer)!);
      case 132:
        return HwpEditHistoryState.decode(readValue(buffer)!);
      case 133:
        return HwpSaveResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HwpHostApi {
  /// Constructor for [HwpHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HwpHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<HwpDocumentInfo> openHwpAsset(
    String assetKey,
    Uint8List assetBytes,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.openHwpAsset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[assetKey, assetBytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpDocumentInfo;
  }

  Future<HwpDocumentInfo> openHwpFile(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.openHwpFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpDocumentInfo;
  }

  Future<HwpDocumentInfo> currentHwpDocumentInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.currentHwpDocumentInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpDocumentInfo;
  }

  Future<void> closeHwpDocument() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.closeHwpDocument$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> extractHwpText() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.extractHwpText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> renderHwpPageSvg(int pageIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.renderHwpPageSvg$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> hitTestHwpPage(int pageIndex, double x, double y) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.hitTestHwpPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex, x, y],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> getHwpCursorRect(
    int sectionIndex,
    int paragraphIndex,
    int charOffset,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.getHwpCursorRect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sectionIndex, paragraphIndex, charOffset],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> insertHwpText(
    int sectionIndex,
    int paragraphIndex,
    int charOffset,
    String text,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.insertHwpText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sectionIndex, paragraphIndex, charOffset, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> deleteHwpText(
    int sectionIndex,
    int paragraphIndex,
    int charOffset,
    int count,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.deleteHwpText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sectionIndex, paragraphIndex, charOffset, count],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> splitHwpParagraph(
    int sectionIndex,
    int paragraphIndex,
    int charOffset,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.splitHwpParagraph$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sectionIndex, paragraphIndex, charOffset],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> mergeHwpParagraph(int sectionIndex, int paragraphIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.mergeHwpParagraph$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sectionIndex, paragraphIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<HwpEditResult> replaceHwpText(HwpReplaceTextRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.replaceHwpText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpEditResult;
  }

  Future<HwpEditHistoryState> hwpEditHistoryState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.hwpEditHistoryState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpEditHistoryState;
  }

  Future<HwpEditHistoryState> undoHwpEdit() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.undoHwpEdit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpEditHistoryState;
  }

  Future<HwpEditHistoryState> redoHwpEdit() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.redoHwpEdit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpEditHistoryState;
  }

  Future<HwpSaveResult> saveHwp() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.saveHwp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpSaveResult;
  }

  Future<HwpSaveResult> exportHwpCopy(String outputPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.HwpHostApi.exportHwpCopy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[outputPath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as HwpSaveResult;
  }
}
