// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Where the pages of a scan session came from. Capture is split by source
/// because the two paths have different guarantees: the camera screen detects
/// the page and corrects its perspective, the photo picker gives whatever the
/// user shot.
enum PdfScanSource { scanner, photoPicker }

/// Enhancement applied to a page. A closed set rather than generic photo
/// knobs, so each one can be regression-tested; named and ordered after
/// CamScanner, because that is what users arrive already knowing.
///
///  - [auto] — picks one of the modes below from the page's content. It never
///    picks [blackAndWhite]; see the classifier in `PdfScanImageProcessor`.
///  - [lighten] — for colourful, well-lit originals whose background is artwork
///    rather than paper. Corrects illumination halfway and never clips to
///    white, because the full treatment flattens a photograph's tonality away.
///  - [magicColor] — the default. Lighting flattened, paper clipped to true
///    white, colour kept and lifted so a stamp or highlighter survives.
///  - [grayMode] — the same, desaturated, stretched wider.
///  - [blackAndWhite] — two tones from a global cut. Crisp and small; right for
///    clean printed text.
///  - [blackAndWhite2] — two tones from a local comparison. Grainier, but it
///    survives faint pencil and lighting the flatten could not remove.
///
/// Uneven lighting is not a preset and not a control: every preset above starts
/// by flattening the page's illumination, so there is nothing for a user to
/// aim.
enum PdfScanPreset { auto, original, lighten, magicColor, grayMode, blackAndWhite, blackAndWhite2 }

/// Output resolution and compression for the exported PDF.
enum PdfScanExportQuality { standard, high }

class PdfScanSessionInfo {
  PdfScanSessionInfo({required this.sessionId, required this.pageCount, required this.source});

  String sessionId;

  int pageCount;

  PdfScanSource source;

  List<Object?> _toList() {
    return <Object?>[sessionId, pageCount, source];
  }

  Object encode() {
    return _toList();
  }

  static PdfScanSessionInfo decode(Object result) {
    result as List<Object?>;
    return PdfScanSessionInfo(
      sessionId: result[0]! as String,
      pageCount: result[1]! as int,
      source: result[2]! as PdfScanSource,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfScanSessionInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfScanSessionInfo(sessionId: $sessionId, pageCount: $pageCount, source: $source)';
  }
}

class PdfScanPageInfo {
  PdfScanPageInfo({
    required this.pageId,
    required this.index,
    required this.preset,
    required this.rotationDegrees,
  });

  String pageId;

  int index;

  PdfScanPreset preset;

  /// Stored as metadata and applied at render/export time only, so rotating a
  /// page never invalidates its processed-image cache.
  int rotationDegrees;

  List<Object?> _toList() {
    return <Object?>[pageId, index, preset, rotationDegrees];
  }

  Object encode() {
    return _toList();
  }

  static PdfScanPageInfo decode(Object result) {
    result as List<Object?>;
    return PdfScanPageInfo(
      pageId: result[0]! as String,
      index: result[1]! as int,
      preset: result[2]! as PdfScanPreset,
      rotationDegrees: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfScanPageInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageId, other.pageId) &&
        _deepEquals(index, other.index) &&
        _deepEquals(preset, other.preset) &&
        _deepEquals(rotationDegrees, other.rotationDegrees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfScanPageInfo(pageId: $pageId, index: $index, preset: $preset, rotationDegrees: $rotationDegrees)';
  }
}

class PdfScanExportRequest {
  PdfScanExportRequest({required this.sessionId, required this.quality, required this.outputPath});

  String sessionId;

  PdfScanExportQuality quality;

  /// Empty means "let the native side choose a path in the session directory".
  String outputPath;

  List<Object?> _toList() {
    return <Object?>[sessionId, quality, outputPath];
  }

  Object encode() {
    return _toList();
  }

  static PdfScanExportRequest decode(Object result) {
    result as List<Object?>;
    return PdfScanExportRequest(
      sessionId: result[0]! as String,
      quality: result[1]! as PdfScanExportQuality,
      outputPath: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfScanExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(quality, other.quality) &&
        _deepEquals(outputPath, other.outputPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfScanExportRequest(sessionId: $sessionId, quality: $quality, outputPath: $outputPath)';
  }
}

class PdfScanExportResult {
  PdfScanExportResult({
    required this.outputPath,
    required this.pageCount,
    required this.fileSizeBytes,
    required this.durationMilliseconds,
    required this.presetSummary,
  });

  String outputPath;

  int pageCount;

  int fileSizeBytes;

  int durationMilliseconds;

  /// Human-readable tally of the presets that produced this file, e.g.
  /// "magicColor x3, original x1". Surfaced in the export confirmation.
  String presetSummary;

  List<Object?> _toList() {
    return <Object?>[outputPath, pageCount, fileSizeBytes, durationMilliseconds, presetSummary];
  }

  Object encode() {
    return _toList();
  }

  static PdfScanExportResult decode(Object result) {
    result as List<Object?>;
    return PdfScanExportResult(
      outputPath: result[0]! as String,
      pageCount: result[1]! as int,
      fileSizeBytes: result[2]! as int,
      durationMilliseconds: result[3]! as int,
      presetSummary: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfScanExportResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(durationMilliseconds, other.durationMilliseconds) &&
        _deepEquals(presetSummary, other.presetSummary);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfScanExportResult(outputPath: $outputPath, pageCount: $pageCount, fileSizeBytes: $fileSizeBytes, durationMilliseconds: $durationMilliseconds, presetSummary: $presetSummary)';
  }
}

/// A PDF the scanner has already produced. Lives in Documents, so it outlives
/// the session that made it.
class PdfScanExportedDocument {
  PdfScanExportedDocument({
    required this.path,
    required this.fileName,
    required this.pageCount,
    required this.fileSizeBytes,
    required this.createdAtEpochMs,
  });

  String path;

  String fileName;

  int pageCount;

  int fileSizeBytes;

  int createdAtEpochMs;

  List<Object?> _toList() {
    return <Object?>[path, fileName, pageCount, fileSizeBytes, createdAtEpochMs];
  }

  Object encode() {
    return _toList();
  }

  static PdfScanExportedDocument decode(Object result) {
    result as List<Object?>;
    return PdfScanExportedDocument(
      path: result[0]! as String,
      fileName: result[1]! as String,
      pageCount: result[2]! as int,
      fileSizeBytes: result[3]! as int,
      createdAtEpochMs: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfScanExportedDocument || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(createdAtEpochMs, other.createdAtEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfScanExportedDocument(path: $path, fileName: $fileName, pageCount: $pageCount, fileSizeBytes: $fileSizeBytes, createdAtEpochMs: $createdAtEpochMs)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PdfScanSource) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PdfScanPreset) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PdfScanExportQuality) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PdfScanSessionInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PdfScanPageInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PdfScanExportRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PdfScanExportResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PdfScanExportedDocument) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfScanSource.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfScanPreset.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfScanExportQuality.values[value];
      case 132:
        return PdfScanSessionInfo.decode(readValue(buffer)!);
      case 133:
        return PdfScanPageInfo.decode(readValue(buffer)!);
      case 134:
        return PdfScanExportRequest.decode(readValue(buffer)!);
      case 135:
        return PdfScanExportResult.decode(readValue(buffer)!);
      case 136:
        return PdfScanExportedDocument.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PdfScanHostApi {
  /// Constructor for [PdfScanHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PdfScanHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Presents the app's own capture screen — live edge detection, auto-capture
  /// and perspective correction, but no colour processing, which the pipeline
  /// does instead. Pages land in a new session; no PDF is produced here.
  Future<void> startDocumentCapture() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.startDocumentCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<List<PdfScanPageInfo>> getScanPages(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.getScanPages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PdfScanPageInfo>();
  }

  Future<void> rotateScanPage(String sessionId, String pageId, int degrees) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.rotateScanPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      pageId,
      degrees,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> deleteScanPage(String sessionId, String pageId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.deleteScanPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      pageId,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> reorderScanPages(String sessionId, List<String> pageIds) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.reorderScanPages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      pageIds,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Reprocesses from the original capture every time, so switching presets
  /// never compounds one enhancement on top of another.
  Future<void> applyPreset(String sessionId, String pageId, PdfScanPreset preset) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.applyPreset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      pageId,
      preset,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> applyPresetToAll(String sessionId, PdfScanPreset preset) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.applyPresetToAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      preset,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Toggles the review canvas between the original capture and the processed
  /// result. Cheap because both are already cached.
  Future<void> setComparingOriginal(String sessionId, bool comparing) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.setComparingOriginal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      comparing,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> showScanPage(String sessionId, String pageId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.showScanPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      sessionId,
      pageId,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> exportScanSessionToPdf(PdfScanExportRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.exportScanSessionToPdf$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> cancelScanOperation(String operationId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.cancelScanOperation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[operationId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Deletes the session directory. Sessions not discarded explicitly are
  /// swept on next launch by age.
  Future<void> discardScanSession(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.discardScanSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Everything the scanner has exported, newest first.
  Future<List<PdfScanExportedDocument>> listExportedScans() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.listExportedScans$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PdfScanExportedDocument>();
  }

  /// Presents the file in Quick Look. Self-contained so the scan library does
  /// not have to reach into the PDF workspace.
  Future<void> openExportedScan(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.openExportedScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> shareExportedScan(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.shareExportedScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> deleteExportedScan(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfScanHostApi.deleteExportedScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}

abstract class PdfScanFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onScanSessionCreated(PdfScanSessionInfo info);

  void onScanSessionCancelled();

  void onScanPagesChanged(String sessionId, List<PdfScanPageInfo> pages);

  void onScanCurrentPageChanged(String sessionId, int pageIndex, int pageCount);

  void onScanPageProcessed(String sessionId, PdfScanPageInfo page);

  void onScanProgress(String operationId, int completedPages, int totalPages);

  void onScanExportCompleted(String operationId, PdfScanExportResult? result, bool cancelled);

  void onScanOperationFailed(String operationId, String code, String message, String? details);

  static void setUp(
    PdfScanFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanSessionCreated$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PdfScanSessionInfo arg_info = args[0]! as PdfScanSessionInfo;
          try {
            api.onScanSessionCreated(arg_info);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanSessionCancelled$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScanSessionCancelled();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanPagesChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_sessionId = args[0]! as String;
          final List<PdfScanPageInfo> arg_pages = (args[1]! as List<Object?>)
              .cast<PdfScanPageInfo>();
          try {
            api.onScanPagesChanged(arg_sessionId, arg_pages);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanCurrentPageChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_sessionId = args[0]! as String;
          final int arg_pageIndex = args[1]! as int;
          final int arg_pageCount = args[2]! as int;
          try {
            api.onScanCurrentPageChanged(arg_sessionId, arg_pageIndex, arg_pageCount);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanPageProcessed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_sessionId = args[0]! as String;
          final PdfScanPageInfo arg_page = args[1]! as PdfScanPageInfo;
          try {
            api.onScanPageProcessed(arg_sessionId, arg_page);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final int arg_completedPages = args[1]! as int;
          final int arg_totalPages = args[2]! as int;
          try {
            api.onScanProgress(arg_operationId, arg_completedPages, arg_totalPages);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanExportCompleted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final PdfScanExportResult? arg_result = args[1] as PdfScanExportResult?;
          final bool arg_cancelled = args[2]! as bool;
          try {
            api.onScanExportCompleted(arg_operationId, arg_result, arg_cancelled);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanOperationFailed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final String arg_code = args[1]! as String;
          final String arg_message = args[2]! as String;
          final String? arg_details = args[3] as String?;
          try {
            api.onScanOperationFailed(arg_operationId, arg_code, arg_message, arg_details);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
