// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PdfMarkupType { highlight, underline, strikeout }

enum PdfCompressionMode { preserve, rasterized }

class PdfRect {
  PdfRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[x, y, width, height];
  }

  Object encode() {
    return _toList();
  }

  static PdfRect decode(Object result) {
    result as List<Object?>;
    return PdfRect(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfRect(x: $x, y: $y, width: $width, height: $height)';
  }
}

class PdfColor {
  PdfColor({required this.argb});

  int argb;

  List<Object?> _toList() {
    return <Object?>[argb];
  }

  Object encode() {
    return _toList();
  }

  static PdfColor decode(Object result) {
    result as List<Object?>;
    return PdfColor(argb: result[0]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfColor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(argb, other.argb);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfColor(argb: $argb)';
  }
}

class PdfDocumentInfo {
  PdfDocumentInfo({
    required this.workingPath,
    required this.pageCount,
    required this.currentPageIndex,
    required this.hasSearchableText,
    required this.isDirty,
  });

  String workingPath;

  int pageCount;

  int currentPageIndex;

  bool hasSearchableText;

  bool isDirty;

  List<Object?> _toList() {
    return <Object?>[
      workingPath,
      pageCount,
      currentPageIndex,
      hasSearchableText,
      isDirty,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PdfDocumentInfo decode(Object result) {
    result as List<Object?>;
    return PdfDocumentInfo(
      workingPath: result[0]! as String,
      pageCount: result[1]! as int,
      currentPageIndex: result[2]! as int,
      hasSearchableText: result[3]! as bool,
      isDirty: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfDocumentInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(workingPath, other.workingPath) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(currentPageIndex, other.currentPageIndex) &&
        _deepEquals(hasSearchableText, other.hasSearchableText) &&
        _deepEquals(isDirty, other.isDirty);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfDocumentInfo(workingPath: $workingPath, pageCount: $pageCount, currentPageIndex: $currentPageIndex, hasSearchableText: $hasSearchableText, isDirty: $isDirty)';
  }
}

class PdfSearchRequest {
  PdfSearchRequest({
    required this.query,
    required this.caseSensitive,
    required this.wholeWord,
  });

  String query;

  bool caseSensitive;

  bool wholeWord;

  List<Object?> _toList() {
    return <Object?>[query, caseSensitive, wholeWord];
  }

  Object encode() {
    return _toList();
  }

  static PdfSearchRequest decode(Object result) {
    result as List<Object?>;
    return PdfSearchRequest(
      query: result[0]! as String,
      caseSensitive: result[1]! as bool,
      wholeWord: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfSearchRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(query, other.query) &&
        _deepEquals(caseSensitive, other.caseSensitive) &&
        _deepEquals(wholeWord, other.wholeWord);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfSearchRequest(query: $query, caseSensitive: $caseSensitive, wholeWord: $wholeWord)';
  }
}

class PdfSearchState {
  PdfSearchState({
    required this.query,
    required this.totalResults,
    required this.activeResultIndex,
    this.activeResultText,
  });

  String query;

  int totalResults;

  int activeResultIndex;

  String? activeResultText;

  List<Object?> _toList() {
    return <Object?>[query, totalResults, activeResultIndex, activeResultText];
  }

  Object encode() {
    return _toList();
  }

  static PdfSearchState decode(Object result) {
    result as List<Object?>;
    return PdfSearchState(
      query: result[0]! as String,
      totalResults: result[1]! as int,
      activeResultIndex: result[2]! as int,
      activeResultText: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfSearchState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(query, other.query) &&
        _deepEquals(totalResults, other.totalResults) &&
        _deepEquals(activeResultIndex, other.activeResultIndex) &&
        _deepEquals(activeResultText, other.activeResultText);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfSearchState(query: $query, totalResults: $totalResults, activeResultIndex: $activeResultIndex, activeResultText: $activeResultText)';
  }
}

class PdfFreeTextRequest {
  PdfFreeTextRequest({
    required this.pageIndex,
    required this.text,
    required this.bounds,
    required this.fontSize,
    required this.textColor,
  });

  int pageIndex;

  String text;

  PdfRect bounds;

  double fontSize;

  PdfColor textColor;

  List<Object?> _toList() {
    return <Object?>[pageIndex, text, bounds, fontSize, textColor];
  }

  Object encode() {
    return _toList();
  }

  static PdfFreeTextRequest decode(Object result) {
    result as List<Object?>;
    return PdfFreeTextRequest(
      pageIndex: result[0]! as int,
      text: result[1]! as String,
      bounds: result[2]! as PdfRect,
      fontSize: result[3]! as double,
      textColor: result[4]! as PdfColor,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfFreeTextRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageIndex, other.pageIndex) &&
        _deepEquals(text, other.text) &&
        _deepEquals(bounds, other.bounds) &&
        _deepEquals(fontSize, other.fontSize) &&
        _deepEquals(textColor, other.textColor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfFreeTextRequest(pageIndex: $pageIndex, text: $text, bounds: $bounds, fontSize: $fontSize, textColor: $textColor)';
  }
}

class PdfFreeTextAreaSelection {
  PdfFreeTextAreaSelection({required this.pageIndex, required this.bounds});

  int pageIndex;

  PdfRect bounds;

  List<Object?> _toList() {
    return <Object?>[pageIndex, bounds];
  }

  Object encode() {
    return _toList();
  }

  static PdfFreeTextAreaSelection decode(Object result) {
    result as List<Object?>;
    return PdfFreeTextAreaSelection(
      pageIndex: result[0]! as int,
      bounds: result[1]! as PdfRect,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfFreeTextAreaSelection ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageIndex, other.pageIndex) &&
        _deepEquals(bounds, other.bounds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfFreeTextAreaSelection(pageIndex: $pageIndex, bounds: $bounds)';
  }
}

class PdfExportResult {
  PdfExportResult({
    required this.outputPath,
    required this.pageCount,
    required this.fileSizeBytes,
  });

  String outputPath;

  int pageCount;

  int fileSizeBytes;

  List<Object?> _toList() {
    return <Object?>[outputPath, pageCount, fileSizeBytes];
  }

  Object encode() {
    return _toList();
  }

  static PdfExportResult decode(Object result) {
    result as List<Object?>;
    return PdfExportResult(
      outputPath: result[0]! as String,
      pageCount: result[1]! as int,
      fileSizeBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfExportResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(pageCount, other.pageCount) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfExportResult(outputPath: $outputPath, pageCount: $pageCount, fileSizeBytes: $fileSizeBytes)';
  }
}

class PdfOcrRequest {
  PdfOcrRequest({
    required this.pageIndexes,
    required this.recognitionLanguages,
    required this.accurateRecognition,
  });

  List<int> pageIndexes;

  List<String> recognitionLanguages;

  bool accurateRecognition;

  List<Object?> _toList() {
    return <Object?>[pageIndexes, recognitionLanguages, accurateRecognition];
  }

  Object encode() {
    return _toList();
  }

  static PdfOcrRequest decode(Object result) {
    result as List<Object?>;
    return PdfOcrRequest(
      pageIndexes: (result[0]! as List<Object?>).cast<int>(),
      recognitionLanguages: (result[1]! as List<Object?>).cast<String>(),
      accurateRecognition: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfOcrRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageIndexes, other.pageIndexes) &&
        _deepEquals(recognitionLanguages, other.recognitionLanguages) &&
        _deepEquals(accurateRecognition, other.accurateRecognition);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfOcrRequest(pageIndexes: $pageIndexes, recognitionLanguages: $recognitionLanguages, accurateRecognition: $accurateRecognition)';
  }
}

class PdfOcrBlock {
  PdfOcrBlock({
    required this.pageIndex,
    required this.text,
    required this.confidence,
    required this.normalizedBoundingBox,
  });

  int pageIndex;

  String text;

  double confidence;

  PdfRect normalizedBoundingBox;

  List<Object?> _toList() {
    return <Object?>[pageIndex, text, confidence, normalizedBoundingBox];
  }

  Object encode() {
    return _toList();
  }

  static PdfOcrBlock decode(Object result) {
    result as List<Object?>;
    return PdfOcrBlock(
      pageIndex: result[0]! as int,
      text: result[1]! as String,
      confidence: result[2]! as double,
      normalizedBoundingBox: result[3]! as PdfRect,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfOcrBlock || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pageIndex, other.pageIndex) &&
        _deepEquals(text, other.text) &&
        _deepEquals(confidence, other.confidence) &&
        _deepEquals(normalizedBoundingBox, other.normalizedBoundingBox);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfOcrBlock(pageIndex: $pageIndex, text: $text, confidence: $confidence, normalizedBoundingBox: $normalizedBoundingBox)';
  }
}

class PdfCompressionRequest {
  PdfCompressionRequest({
    required this.mode,
    required this.rasterDpi,
    required this.jpegQuality,
  });

  PdfCompressionMode mode;

  int rasterDpi;

  double jpegQuality;

  List<Object?> _toList() {
    return <Object?>[mode, rasterDpi, jpegQuality];
  }

  Object encode() {
    return _toList();
  }

  static PdfCompressionRequest decode(Object result) {
    result as List<Object?>;
    return PdfCompressionRequest(
      mode: result[0]! as PdfCompressionMode,
      rasterDpi: result[1]! as int,
      jpegQuality: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfCompressionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mode, other.mode) &&
        _deepEquals(rasterDpi, other.rasterDpi) &&
        _deepEquals(jpegQuality, other.jpegQuality);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfCompressionRequest(mode: $mode, rasterDpi: $rasterDpi, jpegQuality: $jpegQuality)';
  }
}

class PdfCompressionResult {
  PdfCompressionResult({
    required this.outputPath,
    required this.inputBytes,
    required this.outputBytes,
    required this.compressionRatio,
    required this.durationMilliseconds,
    required this.textSelectable,
    required this.annotationsEditable,
    required this.linksFunctional,
    required this.formsFunctional,
    required this.visualQualityNotes,
    required this.warning,
  });

  String outputPath;

  int inputBytes;

  int outputBytes;

  double compressionRatio;

  int durationMilliseconds;

  bool textSelectable;

  bool annotationsEditable;

  bool linksFunctional;

  bool formsFunctional;

  String visualQualityNotes;

  String warning;

  List<Object?> _toList() {
    return <Object?>[
      outputPath,
      inputBytes,
      outputBytes,
      compressionRatio,
      durationMilliseconds,
      textSelectable,
      annotationsEditable,
      linksFunctional,
      formsFunctional,
      visualQualityNotes,
      warning,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PdfCompressionResult decode(Object result) {
    result as List<Object?>;
    return PdfCompressionResult(
      outputPath: result[0]! as String,
      inputBytes: result[1]! as int,
      outputBytes: result[2]! as int,
      compressionRatio: result[3]! as double,
      durationMilliseconds: result[4]! as int,
      textSelectable: result[5]! as bool,
      annotationsEditable: result[6]! as bool,
      linksFunctional: result[7]! as bool,
      formsFunctional: result[8]! as bool,
      visualQualityNotes: result[9]! as String,
      warning: result[10]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PdfCompressionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(inputBytes, other.inputBytes) &&
        _deepEquals(outputBytes, other.outputBytes) &&
        _deepEquals(compressionRatio, other.compressionRatio) &&
        _deepEquals(durationMilliseconds, other.durationMilliseconds) &&
        _deepEquals(textSelectable, other.textSelectable) &&
        _deepEquals(annotationsEditable, other.annotationsEditable) &&
        _deepEquals(linksFunctional, other.linksFunctional) &&
        _deepEquals(formsFunctional, other.formsFunctional) &&
        _deepEquals(visualQualityNotes, other.visualQualityNotes) &&
        _deepEquals(warning, other.warning);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PdfCompressionResult(outputPath: $outputPath, inputBytes: $inputBytes, outputBytes: $outputBytes, compressionRatio: $compressionRatio, durationMilliseconds: $durationMilliseconds, textSelectable: $textSelectable, annotationsEditable: $annotationsEditable, linksFunctional: $linksFunctional, formsFunctional: $formsFunctional, visualQualityNotes: $visualQualityNotes, warning: $warning)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PdfMarkupType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PdfCompressionMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PdfRect) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PdfColor) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PdfDocumentInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PdfSearchRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PdfSearchState) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PdfFreeTextRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PdfFreeTextAreaSelection) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PdfExportResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PdfOcrRequest) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PdfOcrBlock) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PdfCompressionRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PdfCompressionResult) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfMarkupType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PdfCompressionMode.values[value];
      case 131:
        return PdfRect.decode(readValue(buffer)!);
      case 132:
        return PdfColor.decode(readValue(buffer)!);
      case 133:
        return PdfDocumentInfo.decode(readValue(buffer)!);
      case 134:
        return PdfSearchRequest.decode(readValue(buffer)!);
      case 135:
        return PdfSearchState.decode(readValue(buffer)!);
      case 136:
        return PdfFreeTextRequest.decode(readValue(buffer)!);
      case 137:
        return PdfFreeTextAreaSelection.decode(readValue(buffer)!);
      case 138:
        return PdfExportResult.decode(readValue(buffer)!);
      case 139:
        return PdfOcrRequest.decode(readValue(buffer)!);
      case 140:
        return PdfOcrBlock.decode(readValue(buffer)!);
      case 141:
        return PdfCompressionRequest.decode(readValue(buffer)!);
      case 142:
        return PdfCompressionResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PdfPocHostApi {
  /// Constructor for [PdfPocHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PdfPocHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<PdfDocumentInfo> openAssetWorkingCopy(
    String assetKey,
    Uint8List assetBytes,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.openAssetWorkingCopy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[assetKey, assetBytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfDocumentInfo;
  }

  Future<void> closeDocument() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.closeDocument$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PdfDocumentInfo> resetWorkingCopy(
    String assetKey,
    Uint8List assetBytes,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.resetWorkingCopy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[assetKey, assetBytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfDocumentInfo;
  }

  Future<void> goToPage(int pageIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> goToNextPage() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToNextPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> goToPreviousPage() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPreviousPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PdfSearchState> search(PdfSearchRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.search$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfSearchState;
  }

  Future<PdfSearchState> goToNextSearchResult() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToNextSearchResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfSearchState;
  }

  Future<PdfSearchState> goToPreviousSearchResult() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPreviousSearchResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfSearchState;
  }

  Future<void> clearSearch() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearSearch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> getSelectedText() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.getSelectedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> copySelectedText() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.copySelectedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> addMarkupFromCurrentSelection(PdfMarkupType type) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.addMarkupFromCurrentSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[type],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> addFreeText(PdfFreeTextRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.addFreeText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> beginFreeTextAreaSelection() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.beginFreeTextAreaSelection$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setInkModeEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.setInkModeEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clearCurrentInkInput() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearCurrentInkInput$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> commitCurrentInkToPdf() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitCurrentInkToPdf$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteSelectedAnnotation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deleteSelectedAnnotation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> captureElectronicSignature() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.captureElectronicSignature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clearElectronicSignatureCapture() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearElectronicSignatureCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> confirmElectronicSignatureCapture() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.confirmElectronicSignatureCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> beginSignaturePlacement() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.beginSignaturePlacement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resizeSignaturePlacement(double scale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.resizeSignaturePlacement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[scale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> commitSignaturePlacement() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitSignaturePlacement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelSignaturePlacement() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelSignaturePlacement$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteSelectedSignature() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deleteSelectedSignature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PdfExportResult> exportFlattenedCopy() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.exportFlattenedCopy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfExportResult;
  }

  Future<void> rotatePages(List<int> pageIndexes, int degrees) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.rotatePages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndexes, degrees],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deletePages(List<int> pageIndexes) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deletePages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndexes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> duplicatePage(int pageIndex, int destinationIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.duplicatePage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex, destinationIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> movePage(int fromIndex, int toIndex) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.movePage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fromIndex, toIndex],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cropPage(int pageIndex, PdfRect pageBounds) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cropPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex, pageBounds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cropPageToInset(int pageIndex, double insetPoints) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cropPageToInset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pageIndex, insetPoints],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> commitPendingPageReorder() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitPendingPageReorder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelPendingPageReorder() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelPendingPageReorder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PdfExportResult> savePageOperationsCopy() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.savePageOperationsCopy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfExportResult;
  }

  Future<void> runOcr(PdfOcrRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.runOcr$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelOcr() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelOcr$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showOcrResult(PdfOcrBlock block) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.showOcrResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[block],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> compress(PdfCompressionRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.compress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelCompression() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelCompression$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<PdfDocumentInfo> save() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pdf_tool.PdfPocHostApi.save$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PdfDocumentInfo;
  }
}

abstract class PdfPocFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDocumentOpened(PdfDocumentInfo info);

  void onDocumentClosed();

  void onCurrentPageChanged(int pageIndex, int pageCount);

  void onDirtyStateChanged(bool isDirty);

  void onSearchStateChanged(PdfSearchState state);

  void onSelectionChanged(String? selectedText);

  void onFreeTextAreaSelected(PdfFreeTextAreaSelection selection);

  void onOcrProgress(String operationId, int completedPages, int totalPages);

  void onOcrResult(String operationId, PdfOcrBlock block);

  void onOcrCompleted(String operationId, bool cancelled);

  void onCompressionProgress(
    String operationId,
    int completedPages,
    int totalPages,
  );

  void onCompressionCompleted(
    String operationId,
    PdfCompressionResult? result,
    bool cancelled,
  );

  void onOperationFailed(
    String operationId,
    String code,
    String message,
    String? details,
  );

  static void setUp(
    PdfPocFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDocumentOpened$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PdfDocumentInfo arg_info = args[0]! as PdfDocumentInfo;
          try {
            api.onDocumentOpened(arg_info);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDocumentClosed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onDocumentClosed();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onCurrentPageChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_pageIndex = args[0]! as int;
          final int arg_pageCount = args[1]! as int;
          try {
            api.onCurrentPageChanged(arg_pageIndex, arg_pageCount);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDirtyStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_isDirty = args[0]! as bool;
          try {
            api.onDirtyStateChanged(arg_isDirty);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onSearchStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PdfSearchState arg_state = args[0]! as PdfSearchState;
          try {
            api.onSearchStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onSelectionChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String? arg_selectedText = args[0] as String?;
          try {
            api.onSelectionChanged(arg_selectedText);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onFreeTextAreaSelected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PdfFreeTextAreaSelection arg_selection =
              args[0]! as PdfFreeTextAreaSelection;
          try {
            api.onFreeTextAreaSelected(arg_selection);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onOcrProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final int arg_completedPages = args[1]! as int;
          final int arg_totalPages = args[2]! as int;
          try {
            api.onOcrProgress(
              arg_operationId,
              arg_completedPages,
              arg_totalPages,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onOcrResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final PdfOcrBlock arg_block = args[1]! as PdfOcrBlock;
          try {
            api.onOcrResult(arg_operationId, arg_block);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onOcrCompleted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final bool arg_cancelled = args[1]! as bool;
          try {
            api.onOcrCompleted(arg_operationId, arg_cancelled);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onCompressionProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final int arg_completedPages = args[1]! as int;
          final int arg_totalPages = args[2]! as int;
          try {
            api.onCompressionProgress(
              arg_operationId,
              arg_completedPages,
              arg_totalPages,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onCompressionCompleted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final PdfCompressionResult? arg_result =
              args[1] as PdfCompressionResult?;
          final bool arg_cancelled = args[2]! as bool;
          try {
            api.onCompressionCompleted(
              arg_operationId,
              arg_result,
              arg_cancelled,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onOperationFailed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_operationId = args[0]! as String;
          final String arg_code = args[1]! as String;
          final String arg_message = args[2]! as String;
          final String? arg_details = args[3] as String?;
          try {
            api.onOperationFailed(
              arg_operationId,
              arg_code,
              arg_message,
              arg_details,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
