// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum PdfPocApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum PdfMarkupType: Int, CaseIterable {
  case highlight = 0
  case underline = 1
  case strikeout = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfRect: Hashable, CustomStringConvertible {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return PdfRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: PdfRect, rhs: PdfRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.x, rhs.x) && PdfPocApiPigeonInternal.deepEquals(lhs.y, rhs.y) && PdfPocApiPigeonInternal.deepEquals(lhs.width, rhs.width) && PdfPocApiPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfRect")
    PdfPocApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "PdfRect(x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfColor: Hashable, CustomStringConvertible {
  var argb: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfColor? {
    let argb = pigeonVar_list[0] as! Int64

    return PdfColor(
      argb: argb
    )
  }
  func toList() -> [Any?] {
    return [
      argb
    ]
  }
  static func == (lhs: PdfColor, rhs: PdfColor) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.argb, rhs.argb)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfColor")
    PdfPocApiPigeonInternal.deepHash(value: argb, hasher: &hasher)
  }

  public var description: String {
    return "PdfColor(argb: \(String(describing: argb)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfDocumentInfo: Hashable, CustomStringConvertible {
  var workingPath: String
  var pageCount: Int64
  var currentPageIndex: Int64
  var hasSearchableText: Bool
  var isDirty: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfDocumentInfo? {
    let workingPath = pigeonVar_list[0] as! String
    let pageCount = pigeonVar_list[1] as! Int64
    let currentPageIndex = pigeonVar_list[2] as! Int64
    let hasSearchableText = pigeonVar_list[3] as! Bool
    let isDirty = pigeonVar_list[4] as! Bool

    return PdfDocumentInfo(
      workingPath: workingPath,
      pageCount: pageCount,
      currentPageIndex: currentPageIndex,
      hasSearchableText: hasSearchableText,
      isDirty: isDirty
    )
  }
  func toList() -> [Any?] {
    return [
      workingPath,
      pageCount,
      currentPageIndex,
      hasSearchableText,
      isDirty,
    ]
  }
  static func == (lhs: PdfDocumentInfo, rhs: PdfDocumentInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.workingPath, rhs.workingPath) && PdfPocApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount) && PdfPocApiPigeonInternal.deepEquals(lhs.currentPageIndex, rhs.currentPageIndex) && PdfPocApiPigeonInternal.deepEquals(lhs.hasSearchableText, rhs.hasSearchableText) && PdfPocApiPigeonInternal.deepEquals(lhs.isDirty, rhs.isDirty)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfDocumentInfo")
    PdfPocApiPigeonInternal.deepHash(value: workingPath, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: currentPageIndex, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: hasSearchableText, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: isDirty, hasher: &hasher)
  }

  public var description: String {
    return "PdfDocumentInfo(workingPath: \(String(describing: workingPath)), pageCount: \(String(describing: pageCount)), currentPageIndex: \(String(describing: currentPageIndex)), hasSearchableText: \(String(describing: hasSearchableText)), isDirty: \(String(describing: isDirty)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfSearchRequest: Hashable, CustomStringConvertible {
  var query: String
  var caseSensitive: Bool
  var wholeWord: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfSearchRequest? {
    let query = pigeonVar_list[0] as! String
    let caseSensitive = pigeonVar_list[1] as! Bool
    let wholeWord = pigeonVar_list[2] as! Bool

    return PdfSearchRequest(
      query: query,
      caseSensitive: caseSensitive,
      wholeWord: wholeWord
    )
  }
  func toList() -> [Any?] {
    return [
      query,
      caseSensitive,
      wholeWord,
    ]
  }
  static func == (lhs: PdfSearchRequest, rhs: PdfSearchRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.query, rhs.query) && PdfPocApiPigeonInternal.deepEquals(lhs.caseSensitive, rhs.caseSensitive) && PdfPocApiPigeonInternal.deepEquals(lhs.wholeWord, rhs.wholeWord)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfSearchRequest")
    PdfPocApiPigeonInternal.deepHash(value: query, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: caseSensitive, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: wholeWord, hasher: &hasher)
  }

  public var description: String {
    return "PdfSearchRequest(query: \(String(describing: query)), caseSensitive: \(String(describing: caseSensitive)), wholeWord: \(String(describing: wholeWord)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfSearchState: Hashable, CustomStringConvertible {
  var query: String
  var totalResults: Int64
  var activeResultIndex: Int64
  var activeResultText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfSearchState? {
    let query = pigeonVar_list[0] as! String
    let totalResults = pigeonVar_list[1] as! Int64
    let activeResultIndex = pigeonVar_list[2] as! Int64
    let activeResultText: String? = nilOrValue(pigeonVar_list[3])

    return PdfSearchState(
      query: query,
      totalResults: totalResults,
      activeResultIndex: activeResultIndex,
      activeResultText: activeResultText
    )
  }
  func toList() -> [Any?] {
    return [
      query,
      totalResults,
      activeResultIndex,
      activeResultText,
    ]
  }
  static func == (lhs: PdfSearchState, rhs: PdfSearchState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.query, rhs.query) && PdfPocApiPigeonInternal.deepEquals(lhs.totalResults, rhs.totalResults) && PdfPocApiPigeonInternal.deepEquals(lhs.activeResultIndex, rhs.activeResultIndex) && PdfPocApiPigeonInternal.deepEquals(lhs.activeResultText, rhs.activeResultText)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfSearchState")
    PdfPocApiPigeonInternal.deepHash(value: query, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: totalResults, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: activeResultIndex, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: activeResultText, hasher: &hasher)
  }

  public var description: String {
    return "PdfSearchState(query: \(String(describing: query)), totalResults: \(String(describing: totalResults)), activeResultIndex: \(String(describing: activeResultIndex)), activeResultText: \(String(describing: activeResultText)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfFreeTextRequest: Hashable, CustomStringConvertible {
  var pageIndex: Int64
  var text: String
  var bounds: PdfRect
  var fontSize: Double
  var textColor: PdfColor


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfFreeTextRequest? {
    let pageIndex = pigeonVar_list[0] as! Int64
    let text = pigeonVar_list[1] as! String
    let bounds = pigeonVar_list[2] as! PdfRect
    let fontSize = pigeonVar_list[3] as! Double
    let textColor = pigeonVar_list[4] as! PdfColor

    return PdfFreeTextRequest(
      pageIndex: pageIndex,
      text: text,
      bounds: bounds,
      fontSize: fontSize,
      textColor: textColor
    )
  }
  func toList() -> [Any?] {
    return [
      pageIndex,
      text,
      bounds,
      fontSize,
      textColor,
    ]
  }
  static func == (lhs: PdfFreeTextRequest, rhs: PdfFreeTextRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.pageIndex, rhs.pageIndex) && PdfPocApiPigeonInternal.deepEquals(lhs.text, rhs.text) && PdfPocApiPigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && PdfPocApiPigeonInternal.deepEquals(lhs.fontSize, rhs.fontSize) && PdfPocApiPigeonInternal.deepEquals(lhs.textColor, rhs.textColor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfFreeTextRequest")
    PdfPocApiPigeonInternal.deepHash(value: pageIndex, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: text, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: bounds, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: fontSize, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: textColor, hasher: &hasher)
  }

  public var description: String {
    return "PdfFreeTextRequest(pageIndex: \(String(describing: pageIndex)), text: \(String(describing: text)), bounds: \(String(describing: bounds)), fontSize: \(String(describing: fontSize)), textColor: \(String(describing: textColor)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfFreeTextAreaSelection: Hashable, CustomStringConvertible {
  var pageIndex: Int64
  var bounds: PdfRect


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfFreeTextAreaSelection? {
    let pageIndex = pigeonVar_list[0] as! Int64
    let bounds = pigeonVar_list[1] as! PdfRect

    return PdfFreeTextAreaSelection(
      pageIndex: pageIndex,
      bounds: bounds
    )
  }
  func toList() -> [Any?] {
    return [
      pageIndex,
      bounds,
    ]
  }
  static func == (lhs: PdfFreeTextAreaSelection, rhs: PdfFreeTextAreaSelection) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.pageIndex, rhs.pageIndex) && PdfPocApiPigeonInternal.deepEquals(lhs.bounds, rhs.bounds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfFreeTextAreaSelection")
    PdfPocApiPigeonInternal.deepHash(value: pageIndex, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: bounds, hasher: &hasher)
  }

  public var description: String {
    return "PdfFreeTextAreaSelection(pageIndex: \(String(describing: pageIndex)), bounds: \(String(describing: bounds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfExportResult: Hashable, CustomStringConvertible {
  var outputPath: String
  var pageCount: Int64
  var fileSizeBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfExportResult? {
    let outputPath = pigeonVar_list[0] as! String
    let pageCount = pigeonVar_list[1] as! Int64
    let fileSizeBytes = pigeonVar_list[2] as! Int64

    return PdfExportResult(
      outputPath: outputPath,
      pageCount: pageCount,
      fileSizeBytes: fileSizeBytes
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      pageCount,
      fileSizeBytes,
    ]
  }
  static func == (lhs: PdfExportResult, rhs: PdfExportResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfPocApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && PdfPocApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount) && PdfPocApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfExportResult")
    PdfPocApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
    PdfPocApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
  }

  public var description: String {
    return "PdfExportResult(outputPath: \(String(describing: outputPath)), pageCount: \(String(describing: pageCount)), fileSizeBytes: \(String(describing: fileSizeBytes)))"
  }
}

private class PdfPocApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfMarkupType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PdfRect.fromList(self.readValue() as! [Any?])
    case 131:
      return PdfColor.fromList(self.readValue() as! [Any?])
    case 132:
      return PdfDocumentInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return PdfSearchRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return PdfSearchState.fromList(self.readValue() as! [Any?])
    case 135:
      return PdfFreeTextRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return PdfFreeTextAreaSelection.fromList(self.readValue() as! [Any?])
    case 137:
      return PdfExportResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PdfPocApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PdfMarkupType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PdfRect {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PdfColor {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PdfDocumentInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PdfSearchRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PdfSearchState {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PdfFreeTextRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PdfFreeTextAreaSelection {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PdfExportResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PdfPocApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PdfPocApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PdfPocApiPigeonCodecWriter(data: data)
  }
}

class PdfPocApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PdfPocApiPigeonCodec(readerWriter: PdfPocApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfPocHostApi {
  func openAssetWorkingCopy(assetKey: String, assetBytes: FlutterStandardTypedData) throws -> PdfDocumentInfo
  func closeDocument() throws
  func resetWorkingCopy(assetKey: String, assetBytes: FlutterStandardTypedData) throws -> PdfDocumentInfo
  func goToPage(pageIndex: Int64) throws
  func goToNextPage() throws
  func goToPreviousPage() throws
  func search(request: PdfSearchRequest) throws -> PdfSearchState
  func goToNextSearchResult() throws -> PdfSearchState
  func goToPreviousSearchResult() throws -> PdfSearchState
  func clearSearch() throws
  func getSelectedText() throws -> String?
  func copySelectedText() throws
  func addMarkupFromCurrentSelection(type: PdfMarkupType) throws
  func addFreeText(request: PdfFreeTextRequest) throws
  func beginFreeTextAreaSelection() throws
  func setInkModeEnabled(enabled: Bool) throws
  func clearCurrentInkInput() throws
  func commitCurrentInkToPdf() throws
  func deleteSelectedAnnotation() throws
  func captureElectronicSignature() throws
  func clearElectronicSignatureCapture() throws
  func confirmElectronicSignatureCapture() throws
  func beginSignaturePlacement() throws
  func resizeSignaturePlacement(scale: Double) throws
  func commitSignaturePlacement() throws
  func cancelSignaturePlacement() throws
  func deleteSelectedSignature() throws
  func exportFlattenedCopy() throws -> PdfExportResult
  func rotatePages(pageIndexes: [Int64], degrees: Int64) throws
  func deletePages(pageIndexes: [Int64]) throws
  func duplicatePage(pageIndex: Int64, destinationIndex: Int64) throws
  func movePage(fromIndex: Int64, toIndex: Int64) throws
  func cropPage(pageIndex: Int64, pageBounds: PdfRect) throws
  func cropPageToInset(pageIndex: Int64, insetPoints: Double) throws
  func commitPendingPageReorder() throws
  func cancelPendingPageReorder() throws
  func savePageOperationsCopy() throws -> PdfExportResult
  func save() throws -> PdfDocumentInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfPocHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PdfPocApiPigeonCodec.shared }
  /// Sets up an instance of `PdfPocHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfPocHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openAssetWorkingCopyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.openAssetWorkingCopy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAssetWorkingCopyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetKeyArg = args[0] as! String
        let assetBytesArg = args[1] as! FlutterStandardTypedData
        do {
          let result = try api.openAssetWorkingCopy(assetKey: assetKeyArg, assetBytes: assetBytesArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openAssetWorkingCopyChannel.setMessageHandler(nil)
    }
    let closeDocumentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.closeDocument\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeDocumentChannel.setMessageHandler { _, reply in
        do {
          try api.closeDocument()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeDocumentChannel.setMessageHandler(nil)
    }
    let resetWorkingCopyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.resetWorkingCopy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetWorkingCopyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetKeyArg = args[0] as! String
        let assetBytesArg = args[1] as! FlutterStandardTypedData
        do {
          let result = try api.resetWorkingCopy(assetKey: assetKeyArg, assetBytes: assetBytesArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetWorkingCopyChannel.setMessageHandler(nil)
    }
    let goToPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexArg = args[0] as! Int64
        do {
          try api.goToPage(pageIndex: pageIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToPageChannel.setMessageHandler(nil)
    }
    let goToNextPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToNextPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToNextPageChannel.setMessageHandler { _, reply in
        do {
          try api.goToNextPage()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToNextPageChannel.setMessageHandler(nil)
    }
    let goToPreviousPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPreviousPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToPreviousPageChannel.setMessageHandler { _, reply in
        do {
          try api.goToPreviousPage()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToPreviousPageChannel.setMessageHandler(nil)
    }
    let searchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.search\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PdfSearchRequest
        do {
          let result = try api.search(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      searchChannel.setMessageHandler(nil)
    }
    let goToNextSearchResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToNextSearchResult\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToNextSearchResultChannel.setMessageHandler { _, reply in
        do {
          let result = try api.goToNextSearchResult()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToNextSearchResultChannel.setMessageHandler(nil)
    }
    let goToPreviousSearchResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.goToPreviousSearchResult\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToPreviousSearchResultChannel.setMessageHandler { _, reply in
        do {
          let result = try api.goToPreviousSearchResult()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      goToPreviousSearchResultChannel.setMessageHandler(nil)
    }
    let clearSearchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearSearch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSearchChannel.setMessageHandler { _, reply in
        do {
          try api.clearSearch()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearSearchChannel.setMessageHandler(nil)
    }
    let getSelectedTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.getSelectedText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSelectedTextChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSelectedText()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSelectedTextChannel.setMessageHandler(nil)
    }
    let copySelectedTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.copySelectedText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      copySelectedTextChannel.setMessageHandler { _, reply in
        do {
          try api.copySelectedText()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      copySelectedTextChannel.setMessageHandler(nil)
    }
    let addMarkupFromCurrentSelectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.addMarkupFromCurrentSelection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addMarkupFromCurrentSelectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! PdfMarkupType
        do {
          try api.addMarkupFromCurrentSelection(type: typeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addMarkupFromCurrentSelectionChannel.setMessageHandler(nil)
    }
    let addFreeTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.addFreeText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addFreeTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PdfFreeTextRequest
        do {
          try api.addFreeText(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addFreeTextChannel.setMessageHandler(nil)
    }
    let beginFreeTextAreaSelectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.beginFreeTextAreaSelection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      beginFreeTextAreaSelectionChannel.setMessageHandler { _, reply in
        do {
          try api.beginFreeTextAreaSelection()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      beginFreeTextAreaSelectionChannel.setMessageHandler(nil)
    }
    let setInkModeEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.setInkModeEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setInkModeEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setInkModeEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setInkModeEnabledChannel.setMessageHandler(nil)
    }
    let clearCurrentInkInputChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearCurrentInkInput\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCurrentInkInputChannel.setMessageHandler { _, reply in
        do {
          try api.clearCurrentInkInput()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearCurrentInkInputChannel.setMessageHandler(nil)
    }
    let commitCurrentInkToPdfChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitCurrentInkToPdf\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      commitCurrentInkToPdfChannel.setMessageHandler { _, reply in
        do {
          try api.commitCurrentInkToPdf()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      commitCurrentInkToPdfChannel.setMessageHandler(nil)
    }
    let deleteSelectedAnnotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deleteSelectedAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteSelectedAnnotationChannel.setMessageHandler { _, reply in
        do {
          try api.deleteSelectedAnnotation()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteSelectedAnnotationChannel.setMessageHandler(nil)
    }
    let captureElectronicSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.captureElectronicSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureElectronicSignatureChannel.setMessageHandler { _, reply in
        do {
          try api.captureElectronicSignature()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      captureElectronicSignatureChannel.setMessageHandler(nil)
    }
    let clearElectronicSignatureCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.clearElectronicSignatureCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearElectronicSignatureCaptureChannel.setMessageHandler { _, reply in
        do {
          try api.clearElectronicSignatureCapture()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearElectronicSignatureCaptureChannel.setMessageHandler(nil)
    }
    let confirmElectronicSignatureCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.confirmElectronicSignatureCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      confirmElectronicSignatureCaptureChannel.setMessageHandler { _, reply in
        do {
          try api.confirmElectronicSignatureCapture()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      confirmElectronicSignatureCaptureChannel.setMessageHandler(nil)
    }
    let beginSignaturePlacementChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.beginSignaturePlacement\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      beginSignaturePlacementChannel.setMessageHandler { _, reply in
        do {
          try api.beginSignaturePlacement()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      beginSignaturePlacementChannel.setMessageHandler(nil)
    }
    let resizeSignaturePlacementChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.resizeSignaturePlacement\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resizeSignaturePlacementChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let scaleArg = args[0] as! Double
        do {
          try api.resizeSignaturePlacement(scale: scaleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resizeSignaturePlacementChannel.setMessageHandler(nil)
    }
    let commitSignaturePlacementChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitSignaturePlacement\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      commitSignaturePlacementChannel.setMessageHandler { _, reply in
        do {
          try api.commitSignaturePlacement()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      commitSignaturePlacementChannel.setMessageHandler(nil)
    }
    let cancelSignaturePlacementChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelSignaturePlacement\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelSignaturePlacementChannel.setMessageHandler { _, reply in
        do {
          try api.cancelSignaturePlacement()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelSignaturePlacementChannel.setMessageHandler(nil)
    }
    let deleteSelectedSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deleteSelectedSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteSelectedSignatureChannel.setMessageHandler { _, reply in
        do {
          try api.deleteSelectedSignature()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteSelectedSignatureChannel.setMessageHandler(nil)
    }
    let exportFlattenedCopyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.exportFlattenedCopy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportFlattenedCopyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.exportFlattenedCopy()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportFlattenedCopyChannel.setMessageHandler(nil)
    }
    let rotatePagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.rotatePages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rotatePagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexesArg = args[0] as! [Int64]
        let degreesArg = args[1] as! Int64
        do {
          try api.rotatePages(pageIndexes: pageIndexesArg, degrees: degreesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rotatePagesChannel.setMessageHandler(nil)
    }
    let deletePagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.deletePages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deletePagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexesArg = args[0] as! [Int64]
        do {
          try api.deletePages(pageIndexes: pageIndexesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deletePagesChannel.setMessageHandler(nil)
    }
    let duplicatePageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.duplicatePage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      duplicatePageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexArg = args[0] as! Int64
        let destinationIndexArg = args[1] as! Int64
        do {
          try api.duplicatePage(pageIndex: pageIndexArg, destinationIndex: destinationIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      duplicatePageChannel.setMessageHandler(nil)
    }
    let movePageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.movePage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      movePageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromIndexArg = args[0] as! Int64
        let toIndexArg = args[1] as! Int64
        do {
          try api.movePage(fromIndex: fromIndexArg, toIndex: toIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      movePageChannel.setMessageHandler(nil)
    }
    let cropPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cropPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cropPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexArg = args[0] as! Int64
        let pageBoundsArg = args[1] as! PdfRect
        do {
          try api.cropPage(pageIndex: pageIndexArg, pageBounds: pageBoundsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cropPageChannel.setMessageHandler(nil)
    }
    let cropPageToInsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cropPageToInset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cropPageToInsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageIndexArg = args[0] as! Int64
        let insetPointsArg = args[1] as! Double
        do {
          try api.cropPageToInset(pageIndex: pageIndexArg, insetPoints: insetPointsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cropPageToInsetChannel.setMessageHandler(nil)
    }
    let commitPendingPageReorderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.commitPendingPageReorder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      commitPendingPageReorderChannel.setMessageHandler { _, reply in
        do {
          try api.commitPendingPageReorder()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      commitPendingPageReorderChannel.setMessageHandler(nil)
    }
    let cancelPendingPageReorderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.cancelPendingPageReorder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelPendingPageReorderChannel.setMessageHandler { _, reply in
        do {
          try api.cancelPendingPageReorder()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelPendingPageReorderChannel.setMessageHandler(nil)
    }
    let savePageOperationsCopyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.savePageOperationsCopy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      savePageOperationsCopyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.savePageOperationsCopy()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      savePageOperationsCopyChannel.setMessageHandler(nil)
    }
    let saveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfPocHostApi.save\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveChannel.setMessageHandler { _, reply in
        do {
          let result = try api.save()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PdfPocFlutterApiProtocol {
  func onDocumentOpened(info infoArg: PdfDocumentInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDocumentClosed(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCurrentPageChanged(pageIndex pageIndexArg: Int64, pageCount pageCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDirtyStateChanged(isDirty isDirtyArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSearchStateChanged(state stateArg: PdfSearchState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSelectionChanged(selectedText selectedTextArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFreeTextAreaSelected(selection selectionArg: PdfFreeTextAreaSelection, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOperationFailed(operationId operationIdArg: String, code codeArg: String, message messageArg: String, details detailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PdfPocFlutterApi: PdfPocFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PdfPocApiPigeonCodec {
    return PdfPocApiPigeonCodec.shared
  }
  func onDocumentOpened(info infoArg: PdfDocumentInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDocumentOpened\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([infoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDocumentClosed(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDocumentClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCurrentPageChanged(pageIndex pageIndexArg: Int64, pageCount pageCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onCurrentPageChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pageIndexArg, pageCountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDirtyStateChanged(isDirty isDirtyArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onDirtyStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isDirtyArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSearchStateChanged(state stateArg: PdfSearchState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onSearchStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onSelectionChanged(selectedText selectedTextArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onSelectionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([selectedTextArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onFreeTextAreaSelected(selection selectionArg: PdfFreeTextAreaSelection, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onFreeTextAreaSelected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([selectionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOperationFailed(operationId operationIdArg: String, code codeArg: String, message messageArg: String, details detailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfPocFlutterApi.onOperationFailed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([operationIdArg, codeArg, messageArg, detailsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
