// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum PdfScanApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Where the pages of a scan session came from. Capture is split by source
/// because the two paths have different guarantees: VisionKit already applies
/// perspective correction, the photo picker gives whatever the user shot.
enum PdfScanSource: Int, CaseIterable {
  case scanner = 0
  case photoPicker = 1
}

/// Enhancement applied to a page. Kept as a closed set rather than a bag of
/// generic photo knobs: each preset is tuned against fixture images, so it can
/// be regression-tested.
///
/// Uneven lighting is not a preset and not a control: the pipeline detects
/// under-lit regions itself and corrects only those, with the gain bounded. It
/// is deliberately not exposed — a global knob moved parts of the capture that
/// were already correct, and a manual one made the user do the detector's job.
enum PdfScanPreset: Int, CaseIterable {
  case original = 0
  case enhancedColor = 1
  case cleanGrayscale = 2
  case blackAndWhite = 3
}

/// Output resolution and compression for the exported PDF.
enum PdfScanExportQuality: Int, CaseIterable {
  case standard = 0
  case high = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfScanSessionInfo: Hashable, CustomStringConvertible {
  var sessionId: String
  var pageCount: Int64
  var source: PdfScanSource


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfScanSessionInfo? {
    let sessionId = pigeonVar_list[0] as! String
    let pageCount = pigeonVar_list[1] as! Int64
    let source = pigeonVar_list[2] as! PdfScanSource

    return PdfScanSessionInfo(
      sessionId: sessionId,
      pageCount: pageCount,
      source: source
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      pageCount,
      source,
    ]
  }
  static func == (lhs: PdfScanSessionInfo, rhs: PdfScanSessionInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfScanApiPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && PdfScanApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount) && PdfScanApiPigeonInternal.deepEquals(lhs.source, rhs.source)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfScanSessionInfo")
    PdfScanApiPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: source, hasher: &hasher)
  }

  public var description: String {
    return "PdfScanSessionInfo(sessionId: \(String(describing: sessionId)), pageCount: \(String(describing: pageCount)), source: \(String(describing: source)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfScanPageInfo: Hashable, CustomStringConvertible {
  var pageId: String
  var index: Int64
  var preset: PdfScanPreset
  /// Stored as metadata and applied at render/export time only, so rotating a
  /// page never invalidates its processed-image cache.
  var rotationDegrees: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfScanPageInfo? {
    let pageId = pigeonVar_list[0] as! String
    let index = pigeonVar_list[1] as! Int64
    let preset = pigeonVar_list[2] as! PdfScanPreset
    let rotationDegrees = pigeonVar_list[3] as! Int64

    return PdfScanPageInfo(
      pageId: pageId,
      index: index,
      preset: preset,
      rotationDegrees: rotationDegrees
    )
  }
  func toList() -> [Any?] {
    return [
      pageId,
      index,
      preset,
      rotationDegrees,
    ]
  }
  static func == (lhs: PdfScanPageInfo, rhs: PdfScanPageInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfScanApiPigeonInternal.deepEquals(lhs.pageId, rhs.pageId) && PdfScanApiPigeonInternal.deepEquals(lhs.index, rhs.index) && PdfScanApiPigeonInternal.deepEquals(lhs.preset, rhs.preset) && PdfScanApiPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfScanPageInfo")
    PdfScanApiPigeonInternal.deepHash(value: pageId, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: index, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: preset, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
  }

  public var description: String {
    return "PdfScanPageInfo(pageId: \(String(describing: pageId)), index: \(String(describing: index)), preset: \(String(describing: preset)), rotationDegrees: \(String(describing: rotationDegrees)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfScanExportRequest: Hashable, CustomStringConvertible {
  var sessionId: String
  var quality: PdfScanExportQuality
  /// Empty means "let the native side choose a path in the session directory".
  var outputPath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfScanExportRequest? {
    let sessionId = pigeonVar_list[0] as! String
    let quality = pigeonVar_list[1] as! PdfScanExportQuality
    let outputPath = pigeonVar_list[2] as! String

    return PdfScanExportRequest(
      sessionId: sessionId,
      quality: quality,
      outputPath: outputPath
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      quality,
      outputPath,
    ]
  }
  static func == (lhs: PdfScanExportRequest, rhs: PdfScanExportRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfScanApiPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && PdfScanApiPigeonInternal.deepEquals(lhs.quality, rhs.quality) && PdfScanApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfScanExportRequest")
    PdfScanApiPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: quality, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
  }

  public var description: String {
    return "PdfScanExportRequest(sessionId: \(String(describing: sessionId)), quality: \(String(describing: quality)), outputPath: \(String(describing: outputPath)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PdfScanExportResult: Hashable, CustomStringConvertible {
  var outputPath: String
  var pageCount: Int64
  var fileSizeBytes: Int64
  var durationMilliseconds: Int64
  /// Human-readable tally of the presets that produced this file, e.g.
  /// "enhancedColor x3, original x1". Surfaced in the export confirmation.
  var presetSummary: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfScanExportResult? {
    let outputPath = pigeonVar_list[0] as! String
    let pageCount = pigeonVar_list[1] as! Int64
    let fileSizeBytes = pigeonVar_list[2] as! Int64
    let durationMilliseconds = pigeonVar_list[3] as! Int64
    let presetSummary = pigeonVar_list[4] as! String

    return PdfScanExportResult(
      outputPath: outputPath,
      pageCount: pageCount,
      fileSizeBytes: fileSizeBytes,
      durationMilliseconds: durationMilliseconds,
      presetSummary: presetSummary
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      pageCount,
      fileSizeBytes,
      durationMilliseconds,
      presetSummary,
    ]
  }
  static func == (lhs: PdfScanExportResult, rhs: PdfScanExportResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfScanApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && PdfScanApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount) && PdfScanApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes) && PdfScanApiPigeonInternal.deepEquals(lhs.durationMilliseconds, rhs.durationMilliseconds) && PdfScanApiPigeonInternal.deepEquals(lhs.presetSummary, rhs.presetSummary)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfScanExportResult")
    PdfScanApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: durationMilliseconds, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: presetSummary, hasher: &hasher)
  }

  public var description: String {
    return "PdfScanExportResult(outputPath: \(String(describing: outputPath)), pageCount: \(String(describing: pageCount)), fileSizeBytes: \(String(describing: fileSizeBytes)), durationMilliseconds: \(String(describing: durationMilliseconds)), presetSummary: \(String(describing: presetSummary)))"
  }
}

/// A PDF the scanner has already produced. Lives in Documents, so it outlives
/// the session that made it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PdfScanExportedDocument: Hashable, CustomStringConvertible {
  var path: String
  var fileName: String
  var pageCount: Int64
  var fileSizeBytes: Int64
  var createdAtEpochMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfScanExportedDocument? {
    let path = pigeonVar_list[0] as! String
    let fileName = pigeonVar_list[1] as! String
    let pageCount = pigeonVar_list[2] as! Int64
    let fileSizeBytes = pigeonVar_list[3] as! Int64
    let createdAtEpochMs = pigeonVar_list[4] as! Int64

    return PdfScanExportedDocument(
      path: path,
      fileName: fileName,
      pageCount: pageCount,
      fileSizeBytes: fileSizeBytes,
      createdAtEpochMs: createdAtEpochMs
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      fileName,
      pageCount,
      fileSizeBytes,
      createdAtEpochMs,
    ]
  }
  static func == (lhs: PdfScanExportedDocument, rhs: PdfScanExportedDocument) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PdfScanApiPigeonInternal.deepEquals(lhs.path, rhs.path) && PdfScanApiPigeonInternal.deepEquals(lhs.fileName, rhs.fileName) && PdfScanApiPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount) && PdfScanApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes) && PdfScanApiPigeonInternal.deepEquals(lhs.createdAtEpochMs, rhs.createdAtEpochMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfScanExportedDocument")
    PdfScanApiPigeonInternal.deepHash(value: path, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: fileName, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
    PdfScanApiPigeonInternal.deepHash(value: createdAtEpochMs, hasher: &hasher)
  }

  public var description: String {
    return "PdfScanExportedDocument(path: \(String(describing: path)), fileName: \(String(describing: fileName)), pageCount: \(String(describing: pageCount)), fileSizeBytes: \(String(describing: fileSizeBytes)), createdAtEpochMs: \(String(describing: createdAtEpochMs)))"
  }
}

private class PdfScanApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfScanSource(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfScanPreset(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PdfScanExportQuality(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return PdfScanSessionInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return PdfScanPageInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return PdfScanExportRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return PdfScanExportResult.fromList(self.readValue() as! [Any?])
    case 136:
      return PdfScanExportedDocument.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PdfScanApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PdfScanSource {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PdfScanPreset {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PdfScanExportQuality {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PdfScanSessionInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PdfScanPageInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PdfScanExportRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PdfScanExportResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PdfScanExportedDocument {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PdfScanApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PdfScanApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PdfScanApiPigeonCodecWriter(data: data)
  }
}

class PdfScanApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PdfScanApiPigeonCodec(readerWriter: PdfScanApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfScanHostApi {
  /// Presents `VNDocumentCameraViewController`. Pages land in a new session;
  /// no PDF is produced here.
  func startAppleDocumentScan() throws
  /// Presents `PHPickerViewController`. Selected images are copied into a new
  /// session in the order they were picked.
  func pickScanImages() throws
  func getScanPages(sessionId: String) throws -> [PdfScanPageInfo]
  func rotateScanPage(sessionId: String, pageId: String, degrees: Int64) throws
  func deleteScanPage(sessionId: String, pageId: String) throws
  func reorderScanPages(sessionId: String, pageIds: [String]) throws
  /// Reprocesses from the original capture every time, so switching presets
  /// never compounds one enhancement on top of another.
  func applyPreset(sessionId: String, pageId: String, preset: PdfScanPreset) throws
  func applyPresetToAll(sessionId: String, preset: PdfScanPreset) throws
  /// Toggles the review canvas between the original capture and the processed
  /// result. Cheap because both are already cached.
  func setComparingOriginal(sessionId: String, comparing: Bool) throws
  func showScanPage(sessionId: String, pageId: String) throws
  func exportScanSessionToPdf(request: PdfScanExportRequest) throws
  func cancelScanOperation(operationId: String) throws
  /// Deletes the session directory. Sessions not discarded explicitly are
  /// swept on next launch by age.
  func discardScanSession(sessionId: String) throws
  /// Everything the scanner has exported, newest first.
  func listExportedScans() throws -> [PdfScanExportedDocument]
  /// Presents the file in Quick Look. Self-contained so the scan library does
  /// not have to reach into the PDF workspace.
  func openExportedScan(path: String) throws
  func shareExportedScan(path: String) throws
  func deleteExportedScan(path: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfScanHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PdfScanApiPigeonCodec.shared }
  /// Sets up an instance of `PdfScanHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfScanHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Presents `VNDocumentCameraViewController`. Pages land in a new session;
    /// no PDF is produced here.
    let startAppleDocumentScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.startAppleDocumentScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAppleDocumentScanChannel.setMessageHandler { _, reply in
        do {
          try api.startAppleDocumentScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAppleDocumentScanChannel.setMessageHandler(nil)
    }
    /// Presents `PHPickerViewController`. Selected images are copied into a new
    /// session in the order they were picked.
    let pickScanImagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.pickScanImages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickScanImagesChannel.setMessageHandler { _, reply in
        do {
          try api.pickScanImages()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pickScanImagesChannel.setMessageHandler(nil)
    }
    let getScanPagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.getScanPages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScanPagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          let result = try api.getScanPages(sessionId: sessionIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScanPagesChannel.setMessageHandler(nil)
    }
    let rotateScanPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.rotateScanPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rotateScanPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let pageIdArg = args[1] as! String
        let degreesArg = args[2] as! Int64
        do {
          try api.rotateScanPage(sessionId: sessionIdArg, pageId: pageIdArg, degrees: degreesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rotateScanPageChannel.setMessageHandler(nil)
    }
    let deleteScanPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.deleteScanPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteScanPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let pageIdArg = args[1] as! String
        do {
          try api.deleteScanPage(sessionId: sessionIdArg, pageId: pageIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteScanPageChannel.setMessageHandler(nil)
    }
    let reorderScanPagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.reorderScanPages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reorderScanPagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let pageIdsArg = args[1] as! [String]
        do {
          try api.reorderScanPages(sessionId: sessionIdArg, pageIds: pageIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reorderScanPagesChannel.setMessageHandler(nil)
    }
    /// Reprocesses from the original capture every time, so switching presets
    /// never compounds one enhancement on top of another.
    let applyPresetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.applyPreset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyPresetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let pageIdArg = args[1] as! String
        let presetArg = args[2] as! PdfScanPreset
        do {
          try api.applyPreset(sessionId: sessionIdArg, pageId: pageIdArg, preset: presetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyPresetChannel.setMessageHandler(nil)
    }
    let applyPresetToAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.applyPresetToAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyPresetToAllChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let presetArg = args[1] as! PdfScanPreset
        do {
          try api.applyPresetToAll(sessionId: sessionIdArg, preset: presetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyPresetToAllChannel.setMessageHandler(nil)
    }
    /// Toggles the review canvas between the original capture and the processed
    /// result. Cheap because both are already cached.
    let setComparingOriginalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.setComparingOriginal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setComparingOriginalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let comparingArg = args[1] as! Bool
        do {
          try api.setComparingOriginal(sessionId: sessionIdArg, comparing: comparingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setComparingOriginalChannel.setMessageHandler(nil)
    }
    let showScanPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.showScanPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showScanPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let pageIdArg = args[1] as! String
        do {
          try api.showScanPage(sessionId: sessionIdArg, pageId: pageIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showScanPageChannel.setMessageHandler(nil)
    }
    let exportScanSessionToPdfChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.exportScanSessionToPdf\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportScanSessionToPdfChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PdfScanExportRequest
        do {
          try api.exportScanSessionToPdf(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exportScanSessionToPdfChannel.setMessageHandler(nil)
    }
    let cancelScanOperationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.cancelScanOperation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelScanOperationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let operationIdArg = args[0] as! String
        do {
          try api.cancelScanOperation(operationId: operationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelScanOperationChannel.setMessageHandler(nil)
    }
    /// Deletes the session directory. Sessions not discarded explicitly are
    /// swept on next launch by age.
    let discardScanSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.discardScanSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discardScanSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.discardScanSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      discardScanSessionChannel.setMessageHandler(nil)
    }
    /// Everything the scanner has exported, newest first.
    let listExportedScansChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.listExportedScans\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listExportedScansChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listExportedScans()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listExportedScansChannel.setMessageHandler(nil)
    }
    /// Presents the file in Quick Look. Self-contained so the scan library does
    /// not have to reach into the PDF workspace.
    let openExportedScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.openExportedScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openExportedScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.openExportedScan(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openExportedScanChannel.setMessageHandler(nil)
    }
    let shareExportedScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.shareExportedScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shareExportedScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.shareExportedScan(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      shareExportedScanChannel.setMessageHandler(nil)
    }
    let deleteExportedScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_tool.PdfScanHostApi.deleteExportedScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteExportedScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.deleteExportedScan(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteExportedScanChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PdfScanFlutterApiProtocol {
  func onScanSessionCreated(info infoArg: PdfScanSessionInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanSessionCancelled(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanPagesChanged(sessionId sessionIdArg: String, pages pagesArg: [PdfScanPageInfo], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanCurrentPageChanged(sessionId sessionIdArg: String, pageIndex pageIndexArg: Int64, pageCount pageCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanPageProcessed(sessionId sessionIdArg: String, page pageArg: PdfScanPageInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanProgress(operationId operationIdArg: String, completedPages completedPagesArg: Int64, totalPages totalPagesArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanExportCompleted(operationId operationIdArg: String, result resultArg: PdfScanExportResult?, cancelled cancelledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanOperationFailed(operationId operationIdArg: String, code codeArg: String, message messageArg: String, details detailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PdfScanFlutterApi: PdfScanFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PdfScanApiPigeonCodec {
    return PdfScanApiPigeonCodec.shared
  }
  func onScanSessionCreated(info infoArg: PdfScanSessionInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanSessionCreated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([infoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanSessionCancelled(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanSessionCancelled\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanPagesChanged(sessionId sessionIdArg: String, pages pagesArg: [PdfScanPageInfo], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanPagesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, pagesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanCurrentPageChanged(sessionId sessionIdArg: String, pageIndex pageIndexArg: Int64, pageCount pageCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanCurrentPageChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, pageIndexArg, pageCountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanPageProcessed(sessionId sessionIdArg: String, page pageArg: PdfScanPageInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanPageProcessed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, pageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanProgress(operationId operationIdArg: String, completedPages completedPagesArg: Int64, totalPages totalPagesArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([operationIdArg, completedPagesArg, totalPagesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanExportCompleted(operationId operationIdArg: String, result resultArg: PdfScanExportResult?, cancelled cancelledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanExportCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([operationIdArg, resultArg, cancelledArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanOperationFailed(operationId operationIdArg: String, code codeArg: String, message messageArg: String, details detailsArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pdf_tool.PdfScanFlutterApi.onScanOperationFailed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([operationIdArg, codeArg, messageArg, detailsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
